# This file was auto-generated by scripts/generate_model.jl
# Direct 1:1 translation from references/julia/signaling.jl

using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D

@mtkmodel GongBetaAdrenergic begin
    @parameters begin
        c1 = 0.0
        c2 = 7.6026542216873e-7
        c3 = 1.52053084433746e-6
        c4 = 2.5772997811519946e-5
        c5 = 50.0
        c6 = 25.0
        c7 = 1.4749262536873156
        c8 = 5.0e-9
        c9 = 7.5e-8
        c10 = 9.0e-9
        c11 = 1.25
        c12 = 0.97
        c13 = 0.6351032448377582
        c14 = 0.194
        c15 = 0.25000000000000006
        c16 = 0.12702064896755164
        c17 = 50.0
        c18 = 0.01
        c19 = 100.0
        c20 = 100.0
        c21 = 100.0
        c22 = 249.84000000000003
        c23 = 1135.9
        c24 = 37.55
        c25 = 249.84000000000003
        c26 = 1135.9
        c27 = 37.55
        c28 = 10.879999999999999
        c29 = 46.12
        c30 = 37.55
        c31 = 0.010145
        c32 = 0.0035731
        c33 = 0.001469
        c34 = 1.9526e-5
        c35 = 0.1
        c36 = 0.25
        c37 = 0.2
        c38 = 0.001
        c39 = 0.06042857142857143
        c40 = 1.0
        c41 = 20.0
        c42 = 2.5
        c43 = 4.0
        c44 = 50.0
        c45 = 0.8
        c46 = 1.4
        c47 = 3.0
        c48 = 0.0196
        c49 = 0.010234727999999998
        c50 = 0.24814873799999998
        c51 = 0.000155537469
        c52 = 0.035838943571150444
        c53 = 0.40236079649257966
        c54 = 0.031356434101185826
        c55 = 0.10828819624849352
        c56 = 8.242431410629479e-5
        c57 = 0.022394434045337544
        c58 = 4.760000000000001
        c59 = 0.5
        c60 = 0.5664
        c61 = 0.0011071
        c62 = 0.43249289999999996
        c63 = 0.85
        c64 = 0.15000000000000002
        c65 = 0.567
        c66 = 2.449
        c67 = 0.062
        c68 = 1.053
        c69 = 0.012
        c70 = 1.6655
        c71 = 1.8463
        c72 = 1.053
        c73 = 0.1
        c74 = 4.9054
        c75 = 0.25945
        c76 = 4.0
        c77 = 0.05
        c78 = 0.8
        c79 = 0.8
        c80 = 1210.0
        c81 = 1210.0
        c82 = 0.000344155
        c83 = 0.0004655
        c84 = 0.0022749999999999997
        c85 = 0.00035555974999999996
        c86 = 1.0
        c87 = 0.0862335625
        c88 = 1.0
        c89 = 0.159375
        c90 = 0.1
        c91 = 0.0008201374344071999
        c92 = 0.0004442059439999999
        c93 = 0.0020085165768632326
        c94 = 0.001087860356856
        c95 = 1.0
        c96 = 1.0
        c97 = 0.014062500000000002
        c98 = 0.25895250000000003
        c99 = 0.1
        c100 = 0.001087860356856
        c101 = 0.0020085165768632326
        c102 = 0.0004442059439999999
        c103 = 0.0008201374344071999
        c104 = 0.013520986356932154
        c105 = 1.0
        c106 = 0.062
        c107 = 1.0043
        c108 = 1.3574
        c109 = 0.6623
        c110 = 0.031544
        c111 = 0.0852
        c112 = 0.0465
        c113 = 0.4824
        c114 = 0.03135
        c115 = 0.037696
        c116 = 3.3757
        c117 = 41.32
        c118 = 0.8569
        c119 = 0.020360125778433304
        c120 = 0.20650041666666666
        c121 = 0.940733772342427
        c122 = 0.0680903125
        c123 = 0.06355783759423139
        c124 = 0.015265
        c125 = 0.092455
        c126 = 0.0011001
        c127 = 5.7392
        c128 = 0.10988
        c129 = 7.8605
        c130 = 0.01368
        c131 = 0.052811
        c132 = 0.11348
        c133 = 0.48302
        c134 = 0.00098854
        c135 = 0.80737
        c136 = 0.069537
        c137 = 0.317
        c138 = 0.27623
        c139 = 0.002331
        c140 = 0.16305
        c141 = 1.0542
        c142 = 9.9794e-5
        c143 = 0.00011147
        c144 = 0.025
        c145 = 0.002649876540621563
        c146 = 0.020628200529476566
        c147 = 0.10408
        c148 = 0.052633
        c149 = 2.7143e-5
        c150 = 0.26714
        c151 = 0.125
        c152 = 0.0025548
        c153 = 0.0038257
        c154 = 6.6298e-5
        c155 = 0.043003
        c156 = 0.025
        c157 = 0.00051009
        c158 = 0.0006903
        c159 = 1.2702e-6
        c160 = 0.0063064
        c161 = 0.009818852274320626
        c162 = 0.11023440877067497
        c163 = 0.0018963189993149176
        c164 = 0.02128961694197009
        c165 = 0.11145081819456501
        c166 = 0.1027527599725967
        c167 = 0.1365950616248625
    end

    @variables begin
        # State variables with initial conditions
        beta_cav_Gs_aGTP(t) = 0.00685533455220118
        beta_eca_Gs_aGTP(t) = 0.0184630401160325
        beta_cyt_Gs_aGTP(t) = 0.000731426797266862
        beta_cav_Gs_bg(t) = 0.0074626834509494
        beta_eca_Gs_bg(t) = 0.0191020788696145
        beta_cyt_Gs_bg(t) = 0.00115141961261304
        beta_cav_Gs_aGDP(t) = 0.000607348898749425
        beta_eca_Gs_aGDP(t) = 0.000639038753581265
        beta_cyt_Gs_aGDP(t) = 0.00041999281534611
        cAMP_cav(t) = 0.344257659177271
        cAMP_eca(t) = 9.62262190945345
        cAMP_cyt(t) = 0.474028267773051
        beta_cav_Rb1_pka_tot(t) = 0.0148474493496437
        beta_eca_Rb1_pka_tot(t) = 0.2030159857254
        beta_cyt_Rb1_pka_tot(t) = 0.00944459882156118
        beta_cav_Rb1_grk_tot(t) = 1.76916170568022e-10
        beta_eca_Rb1_grk_tot(t) = 8.36801924219387e-10
        beta_cyt_Rb1_grk_tot(t) = 5.01719476559362e-11
        pka_cav_ARC(t) = 0.0898875954193269
        pka_cav_A2RC(t) = 0.00272422687231002
        pka_cav_A2R(t) = 0.225041998219388
        pka_cav_C(t) = 0.032238122010232
        pka_cav_PKIC(t) = 0.192803876209063
        pka_eca_ARC(t) = 0.205457169881723
        pka_eca_A2RC(t) = 0.174050238959555
        pka_eca_A2R(t) = 0.817148066343192
        pka_eca_C(t) = 0.567236181979005
        pka_eca_PKIC(t) = 0.249911884364108
        pka_cyt_ARC(t) = 0.0646981828366729
        pka_cyt_A2RC(t) = 0.0664977613514265
        pka_cyt_A2R(t) = 0.489057632872032
        pka_cyt_C(t) = 0.362107101574369
        pka_cyt_PKIC(t) = 0.126950531297531
        PDE3_P_cav(t) = 0.02339549924788
        PDE3_P_cyt(t) = 0.0128401592747216
        PDE4_P_cav(t) = 0.00629647926927854
        PDE4_P_eca(t) = 4.29166115483698e-5
        PDE4_P_cyt(t) = 0.00917030613498568
        inhib1_p(t) = 0.0123536190564101
        ICaLp(t) = 0.000664158274421826
        IKsp(t) = 0.000765842738691197
        iup_f_plb(t) = 0.666165471397222
        f_tni(t) = 0.673477756497978
        ina_f_ina(t) = 0.236980176272067
        f_inak(t) = 0.124710628782511
        RyRp(t) = 0.00404925913372347
        f_ikur(t) = 0.0589106047787742
        beta_cav_Rb2_pka_tot(t) = 0.0274407333314977
        beta_cav_Rb2_grk_tot(t) = 6.32124571143896e-10
        beta_cav_Gi_aGTP(t) = 0.00159025206300466
        beta_cav_Gi_bg(t) = 0.00209267447556971
        beta_cav_Gi_aGDP(t) = 0.000502422412564797
        beta_eca_Rb2_pka_tot(t) = 0.0110248493074472
        beta_eca_Rb2_grk_tot(t) = 8.04005829146876e-11
        beta_eca_Gi_aGTP(t) = 0.000364313646402573
        beta_eca_Gi_bg(t) = 0.000705654325530757
        beta_eca_Gi_aGDP(t) = 0.000341340679127998

        # Intermediate variables
        beta_cav_Rb1_np_tot(t)
        beta_cav_Rb2_np_tot(t)
        beta_cav_Gi_abg(t)
        beta_cav_Gs_abg(t)
        beta_cav_Gs_f_d(t)
        beta_cav_Gs_f_b(t)
        beta_cav_Gs_f_c(t)
        beta_cav_Gs_f_rr(t)
        beta_cav_Gs_f_yr(t)
        beta_cav_Gs_f_yi(t)
        beta_cav_Gs_f_mag(t)
        beta_cav_Gs_f_arg(t)
        beta_cav_Gs_f_x(t)
        beta_cav_Gs_f_r(t)
        beta_cav_Gs_f_i(t)
        beta_cav_Gs_f(t)
        beta_cav_Rb1_f(t)
        beta_cav_LRb1(t)
        beta_cav_LRb1Gs(t)
        beta_cav_Rb2_f(t)
        beta_cav_LRb2(t)
        beta_cav_Rb2Gs(t)
        beta_cav_Rb1Gs(t)
        beta_cav_LRb2Gs(t)
        beta_eca_Gs_abg(t)
        beta_eca_Rb2_np_tot(t)
        beta_eca_Rb1_np_tot(t)
        beta_eca_Gs_f_d(t)
        beta_eca_Gs_f_c(t)
        beta_eca_Gs_f_b(t)
        beta_eca_Gs_f_rr(t)
        beta_eca_Gs_f_yi(t)
        beta_eca_Gs_f_yr(t)
        beta_eca_Gs_f_mag(t)
        beta_eca_Gs_f_arg(t)
        beta_eca_Gs_f_x(t)
        beta_eca_Gs_f_i(t)
        beta_eca_Gs_f_r(t)
        beta_eca_Gs_f(t)
        beta_eca_Rb1_f(t)
        beta_eca_Rb2_f(t)
        beta_eca_LRb1(t)
        beta_eca_LRb2(t)
        beta_eca_LRb2Gs(t)
        beta_eca_LRb1Gs(t)
        beta_eca_Rb2Gs(t)
        beta_eca_Rb1Gs(t)
        beta_eca_RGs_tot(t)
        beta_eca_LRGs_tot(t)
        beta_eca_Gi_abg(t)
        beta_eca_Rb2_pka_f_c(t)
        beta_eca_Rb2_pka_f_b(t)
        beta_eca_Rb2_pka_f(t)
        beta_cyt_Gs_abg(t)
        beta_cyt_Rb1_np_tot(t)
        beta_cyt_Rb1_np_f_b(t)
        beta_cyt_Rb1_np_f_c(t)
        Rb1_np_f(t)
        beta_cyt_Gs_f(t)
        LRb1_np(t)
        LRb1Gs_np(t)
        Rb1Gs_np(t)
        beta_cav_RGs_tot(t)
        beta_cav_LRGs_tot(t)
        beta_cav_Rb2_pka_f_c(t)
        beta_cav_Rb2_pka_f_b(t)
        beta_cav_Rb2_pka_f(t)
        beta_cav_Gi_f(t)
        beta_cav_Rb2Gi(t)
        beta_cav_LRb2Gi(t)
        beta_eca_Gi_f(t)
        beta_eca_Rb2Gi(t)
        beta_eca_LRb2Gi(t)
        pka_cav_RCf(t)
        pka_eca_RCf(t)
        pka_eca_dcAMP(t)
        pka_cyt_RCf(t)
        pka_cav_dcAMP(t)
        pka_cyt_dcAMP(t)
        dcAMP_PDE2_cyt(t)
        dcAMP_PDE2_eca(t)
        dcAMP_PDE2_cav(t)
        dcAMP_PDE3_cav(t)
        dcAMP_PDE4_cyt(t)
        dcAMP_PDE4_eca(t)
        dcAMP_PDE4_cav(t)
        dcAMP_PDE3_cyt(t)
        camp_cAMP_cyt_pde(t)
        camp_cAMP_cyt_j1(t)
        camp_cAMP_cyt_j2(t)
        camp_cAMP_eca_pde(t)
        camp_cAMP_eca_j2(t)
        camp_cAMP_eca_j1(t)
        camp_cAMP_cav_pde(t)
        camp_cAMP_cav_j2(t)
        camp_cAMP_cav_j1(t)
        ac_kAC47_cyt_gsa(t)
        kAC47_cyt(t)
        ac_kAC56_cav_gsa(t)
        gsi(t)
        kAC56_cav(t)
        ac_kAC47_eca_gsa(t)
        kAC47_eca(t)
        ac_kAC56_cyt_gsa(t)
        kAC56_cyt(t)
        dcAMP_AC47_cyt(t)
        dcAMP_AC56_cyt(t)
        dcAMP_AC56_cav(t)
        dcAMP_AC47_eca(t)
        pp1_PP1f_cyt_sum(t)
        PP1f_cyt(t)
        di(t)
        iks_sig_IKsp_dif(t)
        akap_sig_RyRp_dif(t)
        akap_sig_ICaLp_dif(t)
    end

    @equations begin
    # CAVEOLAR %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    # Total concentration of non-phosphorylated B1AR in the caveolar subspace
    beta_cav_Rb1_np_tot ~ c87 - beta_cav_Rb1_pka_tot - beta_cav_Rb1_grk_tot
    # Total concentration of non-phosphorylated B2AR in the caveolar subspace
    beta_cav_Rb2_np_tot ~ c89 - beta_cav_Rb2_pka_tot - beta_cav_Rb2_grk_tot
    # Concentration of Gi holoenzyme in the caveolar subspace
    beta_cav_Gi_abg ~ c63 * c59 * c5 - beta_cav_Gi_aGTP - beta_cav_Gi_aGDP
    # Concentration of Gs holoenzyme in the caveolar subspace
    beta_cav_Gs_abg ~ c61 * c58 * c5 - beta_cav_Gs_aGTP - beta_cav_Gs_aGDP
    beta_cav_Gs_f_d ~ beta_cav_Gs_abg * c93 / c92
    beta_cav_Gs_f_b ~
        (c94 + c91) / c92 + beta_cav_Rb1_np_tot + beta_cav_Rb2_np_tot -
        beta_cav_Gs_abg
    beta_cav_Gs_f_c ~
        (
            c91 * (beta_cav_Rb1_np_tot - beta_cav_Gs_abg) +
            c94 * (beta_cav_Rb2_np_tot - beta_cav_Gs_abg) +
            c93
        ) / c92
    beta_cav_Gs_f_rr ~ (
        -beta_cav_Gs_f_d / 27.0 * beta_cav_Gs_f_b^3.0 -
        beta_cav_Gs_f_b * beta_cav_Gs_f_b * beta_cav_Gs_f_c * beta_cav_Gs_f_c / 108.0 +
        beta_cav_Gs_f_b * beta_cav_Gs_f_c * beta_cav_Gs_f_d / 6.0 +
        beta_cav_Gs_f_c^3.0 / 27.0 +
        beta_cav_Gs_f_d * beta_cav_Gs_f_d / 4.0
    )
    beta_cav_Gs_f_yr ~ (
        ifelse(beta_cav_Gs_f_rr > 0.0, √(beta_cav_Gs_f_rr), 0.0) +
        beta_cav_Gs_f_d / 2.0 +
        beta_cav_Gs_f_b * beta_cav_Gs_f_c / 6.0 - beta_cav_Gs_f_b^3.0 / 27.0
    )
    beta_cav_Gs_f_yi ~ ifelse(beta_cav_Gs_f_rr < 0.0, √(-beta_cav_Gs_f_rr), 0.0)
    beta_cav_Gs_f_mag ~
        (
            beta_cav_Gs_f_yr * beta_cav_Gs_f_yr + beta_cav_Gs_f_yi * beta_cav_Gs_f_yi
        )^(1.0 / 6.0)
    beta_cav_Gs_f_arg ~ atan(beta_cav_Gs_f_yi / beta_cav_Gs_f_yr) / 3.0
    beta_cav_Gs_f_x ~
        (beta_cav_Gs_f_c / 3.0 - beta_cav_Gs_f_b * beta_cav_Gs_f_b / 9.0) /
        (beta_cav_Gs_f_mag * beta_cav_Gs_f_mag)
    beta_cav_Gs_f_r ~
        beta_cav_Gs_f_mag * cos(beta_cav_Gs_f_arg) * (1.0 - beta_cav_Gs_f_x) -
        beta_cav_Gs_f_b / 3.0
    beta_cav_Gs_f_i ~ beta_cav_Gs_f_mag * sin(beta_cav_Gs_f_arg) * (1.0 + beta_cav_Gs_f_x)
    # Concentration of free Gs in the caveolar subspace
    beta_cav_Gs_f ~ √(beta_cav_Gs_f_r * beta_cav_Gs_f_r + beta_cav_Gs_f_i * beta_cav_Gs_f_i)
    # Concentration of free non-phosphorylated beta1AR in caveolar subspace
    beta_cav_Rb1_f ~
        beta_cav_Rb1_np_tot /
        (1.0 + c1 / c65 + beta_cav_Gs_f * (c67 + c1) / (c66 * c67))
    # Concentration of non-phosphorylated Ligand / Receptor1 complexes in caveolar subspace
    beta_cav_LRb1 ~ c1 * beta_cav_Rb1_f / c65
    # Concentration of non-phosphorylated Ligand /
    # Receptor1 / G-protein complexes in caveolar subspace
    beta_cav_LRb1Gs ~ c1 * beta_cav_Rb1_f * beta_cav_Gs_f / (c66 * c67)
    # Concentration of free non-phosphorylated beta2AR in caveolar subspace
    beta_cav_Rb2_f ~
        beta_cav_Rb2_np_tot /
        (1.0 + c1 / c72 + beta_cav_Gs_f * (c69 + c1) / (c71 * c69))
    # Concentration of non-phosphorylated Ligand /
    # Receptor2 complexes in caveolar subspace
    beta_cav_LRb2 ~ c1 * beta_cav_Rb2_f / c72
    # Concentration of non-phosphorylated Receptor2 /
    # G-protein complexes in caveolar subspace
    beta_cav_Rb2Gs ~ beta_cav_Rb2_f * beta_cav_Gs_f / c71
    # Concentration of non-phosphorylated Receptor1 /
    # G-protein complexes in caveolar subspace
    beta_cav_Rb1Gs ~ beta_cav_Rb1_f * beta_cav_Gs_f / c66
    # Concentration of non-phosphorylated Ligand /
    # Receptor2 / G-protein complexes in caveolar subspace
    beta_cav_LRb2Gs ~ c1 * beta_cav_Rb2_f * beta_cav_Gs_f / (c71 * c69)
    # Concentration of total PKA-phosphorylated beta1 receptors
        D(beta_cav_Rb1_pka_tot) ~
        0.001 * (c84 * pka_cav_C * beta_cav_Rb1_np_tot - c85 * beta_cav_Rb1_pka_tot)
    # Concentration of total GRK-phosphorylated beta1 receptors
        D(beta_cav_Rb1_grk_tot) ~
        0.001 *
        (c83 * c86 * (beta_cav_LRb1 + beta_cav_LRb1Gs) - c82 * beta_cav_Rb1_grk_tot)
    # Concentration of total PKA-phosphorylated beta2 receptors
        D(beta_cav_Rb2_pka_tot) ~
        0.001 * (c84 * pka_cav_C * beta_cav_Rb2_np_tot - c85 * beta_cav_Rb2_pka_tot)
    # Concentration of total GRK-phosphorylated beta2 receptors
        D(beta_cav_Rb2_grk_tot) ~
        0.001 *
        (c83 * c86 * (beta_cav_LRb2 + beta_cav_LRb2Gs) - c82 * beta_cav_Rb2_grk_tot)
    # EXTRACAVEOLAR %%%%%%%%%%%%%%%%%%
    #
    # beta_eca
    #
    # Concentration of Gs holoenzyme in the extracaveolar space
    beta_eca_Gs_abg ~ c60 * c58 * c6 - beta_eca_Gs_aGTP - beta_eca_Gs_aGDP
    # Total concentration of non-phosphorylated B2AR in the extracaveolar space
    beta_eca_Rb2_np_tot ~ c97 - beta_eca_Rb2_pka_tot - beta_eca_Rb2_grk_tot
    # Total concentration of non-phosphorylated B1AR in the extracaveolar space
    beta_eca_Rb1_np_tot ~ c98 - beta_eca_Rb1_pka_tot - beta_eca_Rb1_grk_tot
    beta_eca_Gs_f_d ~ beta_eca_Gs_abg * c101 / c102
    beta_eca_Gs_f_c ~
        (
            c103 * (beta_eca_Rb1_np_tot - beta_eca_Gs_abg) +
            c100 * (beta_eca_Rb2_np_tot - beta_eca_Gs_abg) +
            c101
        ) / c102
    beta_eca_Gs_f_b ~
        (c100 + c103) / c102 + beta_eca_Rb1_np_tot + beta_eca_Rb2_np_tot -
        beta_eca_Gs_abg
    beta_eca_Gs_f_rr ~ (
        -beta_eca_Gs_f_d / 27.0 * beta_eca_Gs_f_b^3.0 -
        beta_eca_Gs_f_b * beta_eca_Gs_f_b * beta_eca_Gs_f_c * beta_eca_Gs_f_c / 108.0 +
        beta_eca_Gs_f_b * beta_eca_Gs_f_c * beta_eca_Gs_f_d / 6.0 +
        beta_eca_Gs_f_c^3.0 / 27.0 +
        beta_eca_Gs_f_d * beta_eca_Gs_f_d / 4.0
    )
    beta_eca_Gs_f_yi ~ ifelse(beta_eca_Gs_f_rr < 0.0, √(-beta_eca_Gs_f_rr), 0.0)
    beta_eca_Gs_f_yr ~ (
        ifelse(beta_eca_Gs_f_rr > 0.0, √(beta_eca_Gs_f_rr), 0.0) +
        beta_eca_Gs_f_d / 2.0 +
        beta_eca_Gs_f_b * beta_eca_Gs_f_c / 6.0 - beta_eca_Gs_f_b^3.0 / 27.0
    )
    beta_eca_Gs_f_mag ~
        (
            beta_eca_Gs_f_yr * beta_eca_Gs_f_yr + beta_eca_Gs_f_yi * beta_eca_Gs_f_yi
        )^(1.0 / 6.0)
    beta_eca_Gs_f_arg ~ atan(beta_eca_Gs_f_yi / beta_eca_Gs_f_yr) / 3.0
    beta_eca_Gs_f_x ~
        (beta_eca_Gs_f_c / 3.0 - beta_eca_Gs_f_b * beta_eca_Gs_f_b / 9.0) /
        (beta_eca_Gs_f_mag * beta_eca_Gs_f_mag)
    beta_eca_Gs_f_i ~ beta_eca_Gs_f_mag * sin(beta_eca_Gs_f_arg) * (1.0 + beta_eca_Gs_f_x)
    beta_eca_Gs_f_r ~
        beta_eca_Gs_f_mag * cos(beta_eca_Gs_f_arg) * (1.0 - beta_eca_Gs_f_x) -
        beta_eca_Gs_f_b / 3.0
    # Concentration of free Gs in the caveolar subspace
    beta_eca_Gs_f ~ √(beta_eca_Gs_f_r * beta_eca_Gs_f_r + beta_eca_Gs_f_i * beta_eca_Gs_f_i)
    # Concentration of free non-phosphorylated beta1AR in the extracaveolar space
    beta_eca_Rb1_f ~
        beta_eca_Rb1_np_tot /
        (1.0 + c1 / c65 + beta_eca_Gs_f * (c67 + c1) / (c66 * c67))
    # Concentration of free non-phosphorylated beta2AR in the extracaveolar space
    beta_eca_Rb2_f ~
        beta_eca_Rb2_np_tot /
        (1.0 + c1 / c72 + beta_eca_Gs_f * (c69 + c1) / (c71 * c69))
    # Concentration of non-phosphorylated Ligand / Receptor1 complexes in the extracaveolar space
    beta_eca_LRb1 ~ c1 * beta_eca_Rb1_f / c65
    # Concentration of non-phosphorylated Ligand / Receptor2 complexes in the extracaveolar space
    beta_eca_LRb2 ~ c1 * beta_eca_Rb2_f / c72
    # Concentration of non-phosphorylated Ligand /
    # Receptor2 / G-protein complexes in the extracaveolar space
    beta_eca_LRb2Gs ~ c1 * beta_eca_Rb2_f * beta_eca_Gs_f / (c71 * c69)
    # Concentration of non-phosphorylated Ligand /
    # Receptor1 / G-protein complexes in the extracaveolar space
    beta_eca_LRb1Gs ~ c1 * beta_eca_Rb1_f * beta_eca_Gs_f / (c66 * c67)
    # Concentration of non-phosphorylated Receptor2 / G-protein complexes in the extracaveolar space
    beta_eca_Rb2Gs ~ beta_eca_Rb2_f * beta_eca_Gs_f / c71
    # Concentration of non-phosphorylated Receptor1 / G-protein complexes in the extracaveolar space
    beta_eca_Rb1Gs ~ beta_eca_Rb1_f * beta_eca_Gs_f / c66
    beta_eca_RGs_tot ~ beta_eca_Rb1Gs + c96 * beta_eca_Rb2Gs
    beta_eca_LRGs_tot ~ beta_eca_LRb1Gs + c96 * beta_eca_LRb2Gs
    # Concentration of Gi holoenzyme in the extracaveolar space
    beta_eca_Gi_abg ~ c64 * c59 * c6 - beta_eca_Gi_aGTP - beta_eca_Gi_aGDP
    beta_eca_Rb2_pka_f_c ~ -beta_eca_Rb2_pka_tot * c70 * c73
    beta_eca_Rb2_pka_f_b ~ (
        beta_eca_Gi_abg * (c1 + c73) - beta_eca_Rb2_pka_tot * (c73 + c1) +
        c70 * c73 * (1.0 + c1 / c68)
    )
    # Concentration of free PKA-phosphorylated beta2AR in the extracaveolar space
    beta_eca_Rb2_pka_f ~
        (
            -beta_eca_Rb2_pka_f_b + √(
                beta_eca_Rb2_pka_f_b * beta_eca_Rb2_pka_f_b -
                4.0 * c99 * beta_eca_Rb2_pka_f_c,
            )
        ) / (2.0 * c99)
    # Concentration of total PKA-phosphorylated beta1 receptors in the extracaveolar space
        D(beta_eca_Rb1_pka_tot) ~
        0.001 * (c84 * pka_eca_C * beta_eca_Rb1_np_tot - c85 * beta_eca_Rb1_pka_tot)
    # Concentration of total GRK-phosphorylated beta1 receptors in the extracaveolar space
        D(beta_eca_Rb1_grk_tot) ~
        0.001 *
        (c83 * c95 * (beta_eca_LRb1 + beta_eca_LRb1Gs) - c82 * beta_eca_Rb1_grk_tot)
    # Concentration of total PKA-phosphorylated beta2 receptors in the extracaveolar space
        D(beta_eca_Rb2_pka_tot) ~
        0.001 * (c84 * pka_eca_C * beta_eca_Rb2_np_tot - c85 * beta_eca_Rb2_pka_tot)
    # Concentration of total GRK-phosphorylated beta2 receptors in the extracaveolar space
        D(beta_eca_Rb2_grk_tot) ~
        0.001 *
        (c83 * c95 * (beta_eca_LRb2 + beta_eca_LRb2Gs) - c82 * beta_eca_Rb2_grk_tot)
    # CYTOPLASM %%%%%%%%%%%
    # Concentration of Gs holoenzyme in the cytoplasm
    beta_cyt_Gs_abg ~ c62 * c58 * c7 - beta_cyt_Gs_aGTP - beta_cyt_Gs_aGDP
    # Total concentration of non-phosphorylated beta-1 AR in the cytoplasm
    beta_cyt_Rb1_np_tot ~ c104 - beta_cyt_Rb1_pka_tot - beta_cyt_Rb1_grk_tot
    beta_cyt_Rb1_np_f_b ~ (
        beta_cyt_Gs_abg * (c67 + c1) - beta_cyt_Rb1_np_tot * (c67 + c1) +
        c66 * c67 * (1.0 + c1 / c65)
    )
    beta_cyt_Rb1_np_f_c ~ -beta_cyt_Rb1_np_tot * c67 * c66
    # Concentration of free non-phosphorylated beta-1 AR in the cytoplasm
    Rb1_np_f ~
        (
            -beta_cyt_Rb1_np_f_b + √(
                beta_cyt_Rb1_np_f_b * beta_cyt_Rb1_np_f_b -
                4.0 * c106 * beta_cyt_Rb1_np_f_c,
            )
        ) / (2.0 * c106)
    # Concentration of free (non-complexed) Gi in the cytoplasm
    beta_cyt_Gs_f ~ beta_cyt_Gs_abg / (1.0 + Rb1_np_f / c66 * (1.0 + c1 / c67))
    # Concentration of non-phosphorylated ligand / beta-1 AR complexes in the cytoplasm
    LRb1_np ~ c1 * Rb1_np_f / c65
    # Concentration of non-phosphorylated ligand / beta-1 AR / Gs complexes in the cytoplasm
    LRb1Gs_np ~ c1 * Rb1_np_f * beta_cyt_Gs_f / (c66 * c67)
    # Concentration of non-phosphorylated beta-1 AR / Gs complexes in the cytoplasm
    Rb1Gs_np ~ beta_cyt_Gs_f * Rb1_np_f / c66
    # Concentration of total PKA-phosphorylated receptors in the cytoplasm
        D(beta_cyt_Rb1_pka_tot) ~
        0.001 * (c84 * pka_cyt_C * beta_cyt_Rb1_np_tot - c85 * beta_cyt_Rb1_pka_tot)
    # Concentration of total GRK-phosphorylated receptors in the cytoplasm
        D(beta_cyt_Rb1_grk_tot) ~ 0.001 * (c83 * c105 * (LRb1_np + LRb1Gs_np) - c82 * beta_cyt_Rb1_grk_tot)
    # function Mod_GprotAct() in the other version %%%
    beta_cav_RGs_tot ~ beta_cav_Rb1Gs + c88 * beta_cav_Rb2Gs
    beta_cav_LRGs_tot ~ beta_cav_LRb1Gs + c88 * beta_cav_LRb2Gs
    beta_cav_Rb2_pka_f_c ~ -beta_cav_Rb2_pka_tot * c70 * c73
    beta_cav_Rb2_pka_f_b ~ (
        beta_cav_Gi_abg * (c1 + c73) - beta_cav_Rb2_pka_tot * (c73 + c1) +
        c70 * c73 * (1.0 + c1 / c68)
    )
    # Concentration of free PKA-phosphorylated beta2AR in the caveolar subspace
    beta_cav_Rb2_pka_f ~
        (
            -beta_cav_Rb2_pka_f_b + √(
                beta_cav_Rb2_pka_f_b * beta_cav_Rb2_pka_f_b -
                4.0 * c90 * beta_cav_Rb2_pka_f_c,
            )
        ) / (2.0 * c90)
    # Concentration of free (non-complexed) Gi in the caveolar subspace
    beta_cav_Gi_f ~
        beta_cav_Gi_abg / (1.0 + beta_cav_Rb2_pka_f / c70 * (1.0 + c1 / c73))
    # Concentration of PKA phosphorylated b2AR/Gi complexes in caveolar subspace
    beta_cav_Rb2Gi ~ beta_cav_Rb2_pka_f * beta_cav_Gi_f / c70
    # Concentration of PKA phosphorylated Ligand/b2AR/Gi complexes in caveolar subspace
    beta_cav_LRb2Gi ~ beta_cav_Rb2Gi * c1 / c73
    # Concentration of free (non-complexed) Gi in the extracaveolar space
    beta_eca_Gi_f ~
        beta_eca_Gi_abg / (1.0 + beta_eca_Rb2_pka_f / c70 * (1.0 + c1 / c73))
    # Concentration of PKA phosphorylated b2AR/Gi complexes in extracaveolar space
    beta_eca_Rb2Gi ~ beta_eca_Rb2_pka_f * beta_eca_Gi_f / c70
    # Concentration of PKA phosphorylated Ligand/b2AR/Gi complexes in extracaveolar space
    beta_eca_LRb2Gi ~ c1 / c73 * beta_eca_Rb2Gi
    # Concentration of active Gs alpha subunit in caveolar subspace (tri-phosphate)
        D(beta_cav_Gs_aGTP) ~
        0.001 *
        (c75 * beta_cav_RGs_tot + c74 * beta_cav_LRGs_tot - c78 * beta_cav_Gs_aGTP)
    # Concentration of active Gi alpha subunit in caveolar subspace
        D(beta_cav_Gi_aGTP) ~
        0.001 *
        (c77 * beta_cav_Rb2Gi + c76 * beta_cav_LRb2Gi - c79 * beta_cav_Gi_aGTP)
    # Concentration of active Gs alpha subunit in the extracaveolar space (tri-phosphate)
        D(beta_eca_Gs_aGTP) ~
        0.001 *
        (c75 * beta_eca_RGs_tot + c74 * beta_eca_LRGs_tot - c78 * beta_eca_Gs_aGTP)
    # Concentration of active Gi alpha subunit in the extracaveolar space
        D(beta_eca_Gi_aGTP) ~
        0.001 *
        (c77 * beta_eca_Rb2Gi + c76 * beta_eca_LRb2Gi - c79 * beta_eca_Gi_aGTP)
    # Concentration of active Gs alpha subunit in cytoplasm
        D(beta_cyt_Gs_aGTP) ~ 0.001 * (c75 * Rb1Gs_np + c74 * LRb1Gs_np - c78 * beta_cyt_Gs_aGTP)
    # Concentration of active Gs beta-gamma subunit in caveolar subspace
        D(beta_cav_Gs_bg) ~
        0.001 * (
            c75 * beta_cav_RGs_tot + c74 * beta_cav_LRGs_tot -
            c80 * beta_cav_Gs_bg * beta_cav_Gs_aGDP
        )
    # Concentration of active Gi beta-gamma subunit in caveolar subspace
        D(beta_cav_Gi_bg) ~
        0.001 * (
            c77 * beta_cav_Rb2Gi + c76 * beta_cav_LRb2Gi -
            c81 * beta_cav_Gi_bg * beta_cav_Gi_aGDP
        )
    # Concentration of active Gs beta-gamma subunit in the extracaveolar space
        D(beta_eca_Gs_bg) ~
        0.001 * (
            c75 * beta_eca_RGs_tot + c74 * beta_eca_LRGs_tot -
            c80 * beta_eca_Gs_bg * beta_eca_Gs_aGDP
        )
    # Concentration of active Gi beta-gamma subunit in the extracaveolar space
        D(beta_eca_Gi_bg) ~
        0.001 * (
            c77 * beta_eca_Rb2Gi + c76 * beta_eca_LRb2Gi -
            c81 * beta_eca_Gi_bg * beta_eca_Gi_aGDP
        )
    # Concentration of active Gs beta-gamma subunit in cytoplasm
        D(beta_cyt_Gs_bg) ~
        0.001 *
        (c75 * Rb1Gs_np + c74 * LRb1Gs_np - c80 * beta_cyt_Gs_bg * beta_cyt_Gs_aGDP)
    # Concentration of inactive Gs alpha subunit in caveolar subspace (di-phosphate)
        D(beta_cav_Gs_aGDP) ~ 0.001 * (c78 * beta_cav_Gs_aGTP - c80 * beta_cav_Gs_bg * beta_cav_Gs_aGDP)
    # Concentration of inactive Gi alpha subunit in caveolar subspace
        D(beta_cav_Gi_aGDP) ~ 0.001 * (c79 * beta_cav_Gi_aGTP - c81 * beta_cav_Gi_bg * beta_cav_Gi_aGDP)
    # Concentration of inactive Gs alpha subunit in the extracaveolar space (di-phosphate)
        D(beta_eca_Gs_aGDP) ~ 0.001 * (c78 * beta_eca_Gs_aGTP - c80 * beta_eca_Gs_bg * beta_eca_Gs_aGDP)
    # Concentration of inactive Gi alpha subunit in the extracaveolar space
        D(beta_eca_Gi_aGDP) ~ 0.001 * (c79 * beta_eca_Gi_aGTP - c81 * beta_eca_Gi_bg * beta_eca_Gi_aGDP)
    # Concentration of inactive Gs alpha subunit in cytoplasm
        D(beta_cyt_Gs_aGDP) ~ 0.001 * (c78 * beta_cyt_Gs_aGTP - c80 * beta_cyt_Gs_bg * beta_cyt_Gs_aGDP)
    # function Mod_AC()
    # only calculating constants, but does not compute derivative of state
    # variables
    # function Mod_PKA() in the other version %%%%%%%%%%
    # Concentration of free PKA RC subunits in the caveolar compartment
    pka_cav_RCf ~ c12 - pka_cav_ARC - pka_cav_A2RC - pka_cav_A2R
    # Caveolar concentration of PKA RC dimer with 1 cAMP molecule bound
        D(pka_cav_ARC) ~
        0.001 * (
            c19 * pka_cav_RCf * cAMP_cav - c22 * pka_cav_ARC -
            c20 * pka_cav_ARC * cAMP_cav + c23 * pka_cav_A2RC
        )
    # Caveolar concentration of PKA RC dimer with 2 cAMP molecules bound
        D(pka_cav_A2RC) ~
        0.001 * (
            c20 * pka_cav_ARC * cAMP_cav - (c23 + c21) * pka_cav_A2RC +
            c24 * pka_cav_A2R * pka_cav_C
        )
    # Caveolar concentration of PKA R subunit with 2 cAMP molecules bound
        D(pka_cav_A2R) ~ 0.001 * (c21 * pka_cav_A2RC - c24 * pka_cav_A2R * pka_cav_C)
    # Caveolar concentration of free PKA catalytic subunit
        D(pka_cav_C) ~
        0.001 * (
            c21 * pka_cav_A2RC - c24 * pka_cav_A2R * pka_cav_C + c18 * pka_cav_PKIC -
            c17 * (c14 - pka_cav_PKIC) * pka_cav_C
        )
    # Caveolar concentration of free PKI inactivated PKA C subunit
        D(pka_cav_PKIC) ~ 0.001 * (c17 * (c14 - pka_cav_PKIC) * pka_cav_C - c18 * pka_cav_PKIC)
    # Concentration of free PKA RC subunits in the Extracaveolar compartment
    pka_eca_RCf ~ c11 - pka_eca_ARC - pka_eca_A2RC - pka_eca_A2R
    # Extracaveolar rate of change in free cAMP through binding by PKA
    pka_eca_dcAMP ~ (
        -c19 * pka_eca_RCf * cAMP_eca + c25 * pka_eca_ARC -
        c20 * pka_eca_ARC * cAMP_eca + c26 * pka_eca_A2RC
    )
    # Extracaveolar concentration of PKA RC dimer with 1 cAMP molecule bound
        D(pka_eca_ARC) ~
        0.001 * (
            c19 * pka_eca_RCf * cAMP_eca - c25 * pka_eca_ARC -
            c20 * pka_eca_ARC * cAMP_eca + c26 * pka_eca_A2RC
        )
    # Extracaveolar concentration of PKA RC dimer with 2 cAMP molecules bound
        D(pka_eca_A2RC) ~
        0.001 * (
            c20 * pka_eca_ARC * cAMP_eca - (c26 + c21) * pka_eca_A2RC +
            c27 * pka_eca_A2R * pka_eca_C
        )
    # Extracaveolar concentration of PKA R subunit with 2 cAMP molecules bound
        D(pka_eca_A2R) ~ 0.001 * (c21 * pka_eca_A2RC - c27 * pka_eca_A2R * pka_eca_C)
    # Extracaveolar concentration of free PKA catalytic subunit
        D(pka_eca_C) ~
        0.001 * (
            c21 * pka_eca_A2RC - c27 * pka_eca_A2R * pka_eca_C + c18 * pka_eca_PKIC -
            c17 * (c15 - pka_eca_PKIC) * pka_eca_C
        )
    # Extracaveolar concentration of free PKI inactivated PKA C subunit
        D(pka_eca_PKIC) ~ 0.001 * (c17 * (c15 - pka_eca_PKIC) * pka_eca_C - c18 * pka_eca_PKIC)
    # Concentration of free PKA RC subunits in the Cytosolic compartment
    pka_cyt_RCf ~ c13 - pka_cyt_ARC - pka_cyt_A2RC - pka_cyt_A2R
    # Cytosolic concentration of PKA RC dimer with 1 cAMP molecule bound
        D(pka_cyt_ARC) ~
        0.001 * (
            c19 * pka_cyt_RCf * cAMP_cyt - c28 * pka_cyt_ARC -
            c20 * pka_cyt_ARC * cAMP_cyt + c29 * pka_cyt_A2RC
        )
    # Cytosolic concentration of PKA RC dimer with 2 cAMP molecules bound
        D(pka_cyt_A2RC) ~
        0.001 * (
            c20 * pka_cyt_ARC * cAMP_cyt - (c29 + c21) * pka_cyt_A2RC +
            c30 * pka_cyt_A2R * pka_cyt_C
        )
    # Cytosolic concentration of PKA R subunit with 2 cAMP molecules bound
        D(pka_cyt_A2R) ~ 0.001 * (c21 * pka_cyt_A2RC - c30 * pka_cyt_A2R * pka_cyt_C)
    # Cytosolic concentration of free PKA catalytic subunit
        D(pka_cyt_C) ~
        0.001 * (
            c21 * pka_cyt_A2RC - c30 * pka_cyt_A2R * pka_cyt_C + c18 * pka_cyt_PKIC -
            c17 * (c16 - pka_cyt_PKIC) * pka_cyt_C
        )
    # Cytosolic concentration of free PKI inactivated PKA C subunit
        D(pka_cyt_PKIC) ~ 0.001 * (c17 * (c16 - pka_cyt_PKIC) * pka_cyt_C - c18 * pka_cyt_PKIC)
    # function Mod_cAMP() in the other version
    # Caveolar rate of change in free cAMP through binding by PKA
    pka_cav_dcAMP ~ (
        -c19 * pka_cav_RCf * cAMP_cav + c22 * pka_cav_ARC -
        c20 * pka_cav_ARC * cAMP_cav + c23 * pka_cav_A2RC
    )
    # Cytosolic rate of change in free cAMP through binding by PKA
    pka_cyt_dcAMP ~ (
        -c19 * pka_cyt_RCf * cAMP_cyt + c28 * pka_cyt_ARC -
        c20 * pka_cyt_ARC * cAMP_cyt + c29 * pka_cyt_A2RC
    )
    # PDE
    # Rate of cAMP degradation by PDE2 in cytosolic subspace
    dcAMP_PDE2_cyt ~ c52 * c41 / (1.0 + c44 / cAMP_cyt)
    # Rate of cAMP degradation by PDE2 in extracaveolar subspace
    dcAMP_PDE2_eca ~ c51 * c41 / (1.0 + c44 / cAMP_eca)
    # Rate of cAMP degradation by PDE2 in caveolar subspace
    dcAMP_PDE2_cav ~ c50 * c41 / (1.0 + c44 / cAMP_cav)
    # Rate of cAMP degradation by PDE3 in caveolar subspace
    dcAMP_PDE3_cav ~ (c53 + (c47 - 1.0) * PDE3_P_cav) * c42 / (1.0 + c45 / cAMP_cav)
    # Rate of cAMP degradation by PDE4 in cytosolic subspace
    dcAMP_PDE4_cyt ~ (c57 + (c47 - 1.0) * PDE4_P_cyt) * c43 / (1.0 + c46 / cAMP_cyt)
    # Rate of cAMP degradation by PDE4 in extracaveolar subspace
    dcAMP_PDE4_eca ~ (c56 + (c47 - 1.0) * PDE4_P_eca) * c43 / (1.0 + c46 / cAMP_eca)
    # Rate of cAMP degradation by PDE4 in caveolar subspace
    dcAMP_PDE4_cav ~ (c55 + (c47 - 1.0) * PDE4_P_cav) * c43 / (1.0 + c46 / cAMP_cav)
    # Rate of cAMP degradation by PDE3 in cytosolic subspace
    dcAMP_PDE3_cyt ~ (c54 + (c47 - 1.0) * PDE3_P_cyt) * c42 / (1.0 + c45 / cAMP_cyt)
    camp_cAMP_cyt_pde ~ dcAMP_PDE2_cyt + dcAMP_PDE3_cyt + dcAMP_PDE4_cyt
    camp_cAMP_cyt_j1 ~ c9 * (cAMP_cav - cAMP_cyt) / c4
    camp_cAMP_cyt_j2 ~ c10 * (cAMP_eca - cAMP_cyt) / c4
    camp_cAMP_eca_pde ~ dcAMP_PDE2_eca + dcAMP_PDE4_eca
    camp_cAMP_eca_j2 ~ c10 * (cAMP_eca - cAMP_cyt) / c3
    camp_cAMP_eca_j1 ~ c8 * (cAMP_cav - cAMP_eca) / c3
    camp_cAMP_cav_pde ~ dcAMP_PDE2_cav + dcAMP_PDE3_cav + dcAMP_PDE4_cav
    camp_cAMP_cav_j2 ~ c9 * (cAMP_cav - cAMP_cyt) / c2
    camp_cAMP_cav_j1 ~ c8 * (cAMP_cav - cAMP_eca) / c2
    # ac
    #
    ac_kAC47_cyt_gsa ~ beta_cyt_Gs_aGTP^c107
    kAC47_cyt ~ c116 * (c114 + ac_kAC47_cyt_gsa / (c110 + ac_kAC47_cyt_gsa))
    ac_kAC56_cav_gsa ~ beta_cav_Gs_aGTP^c108
    gsi ~ beta_cav_Gs_aGTP^c109
    kAC56_cav ~ (
        c117 *
        (c115 + ac_kAC56_cav_gsa / (c111 + ac_kAC56_cav_gsa)) *
        (
            1.0 -
            (1.0 - c118 * gsi / (c113 + gsi)) * beta_cav_Gi_bg /
            (c112 + beta_cav_Gi_bg)
        )
    )
    ac_kAC47_eca_gsa ~ beta_eca_Gs_aGTP^c107
    kAC47_eca ~ c116 * (c114 + ac_kAC47_eca_gsa / (c110 + ac_kAC47_eca_gsa))
    ac_kAC56_cyt_gsa ~ beta_cyt_Gs_aGTP^c108
    kAC56_cyt ~ c117 * (c115 + ac_kAC56_cyt_gsa / (c111 + ac_kAC56_cyt_gsa))
    # Rate of cAMP production by AC type 4/7 in cytoplasm
    dcAMP_AC47_cyt ~ kAC47_cyt * c119 * c121
    # Rate of cAMP production by AC type 5/6 in cytoplasm
    dcAMP_AC56_cyt ~ kAC56_cyt * c123 * c121
    # Rate of cAMP production by AC type 5/6 in caveolar subspace
    dcAMP_AC56_cav ~ kAC56_cav * c120 * c121
    # Rate of cAMP production by AC type 4/7 in extracaveolar subspace
    dcAMP_AC47_eca ~ kAC47_eca * c122 * c121
    # Caveolar concentration of cAMP
        D(cAMP_cav) ~
        0.001 * (
            pka_cav_dcAMP + dcAMP_AC56_cav - camp_cAMP_cav_pde - camp_cAMP_cav_j1 -
            camp_cAMP_cav_j2
        )
    # Extracaveolar concentration of cAMP
        D(cAMP_eca) ~
        0.001 * (
            pka_eca_dcAMP + dcAMP_AC47_eca - camp_cAMP_eca_pde + camp_cAMP_eca_j1 -
            camp_cAMP_eca_j2
        )
    # Cytosolic concentration of cAMP
        D(cAMP_cyt) ~
        0.001 * (
            pka_cyt_dcAMP + dcAMP_AC47_cyt + dcAMP_AC56_cyt - camp_cAMP_cyt_pde +
            camp_cAMP_cyt_j1 +
            camp_cAMP_cyt_j2
        )
    # Mod_PDE_Phosphorylation() function
    # Concentration of phosphorylated PDE3 in the caveolar subspace
        D(PDE3_P_cav) ~ 0.001 * (c48 * pka_cav_C * (c53 - PDE3_P_cav) - c49 * PDE3_P_cav)
    # Concentration of phosphorylated PDE3 in the cytosolic subspace
        D(PDE3_P_cyt) ~ 0.001 * (c48 * pka_cyt_C * (c54 - PDE3_P_cyt) - c49 * PDE3_P_cyt)
    # Concentration of phosphorylated PDE4 in the caveolar subspace
        D(PDE4_P_cav) ~ 0.001 * (c48 * pka_cav_C * (c55 - PDE4_P_cav) - c49 * PDE4_P_cav)
    # Concentration of phosphorylated PDE4 in the extracaveolar subspace
        D(PDE4_P_eca) ~ 0.001 * (c48 * pka_eca_C * (c56 - PDE4_P_eca) - c49 * PDE4_P_eca)
    # Concentration of phosphorylated PDE4 in the cytosolic subspace
        D(PDE4_P_cyt) ~ 0.001 * (c48 * pka_cyt_C * (c57 - PDE4_P_cyt) - c49 * PDE4_P_cyt)
    # Mod_PP1_Inhibition()
    pp1_PP1f_cyt_sum ~ c38 - c37 + inhib1_p
    # Concentration of uninhibited PP1 in the cytosolic compartment
    PP1f_cyt ~ 0.5 * (√(pp1_PP1f_cyt_sum^2.0 + 4.0 * c38 * c37) - pp1_PP1f_cyt_sum)
    di ~ c39 - inhib1_p
    # Concentration of phosphorylated PP1 inhibitor 1 (cytoplasmic)
        D(inhib1_p) ~
        0.001 * (
            c31 * pka_cyt_C * di / (c33 + di) -
            c32 * c40 * inhib1_p / (c34 + inhib1_p)
        )
    # Mod_Channel_Phosphorylation()
    # Substrates without AKAP
    # Fraction of phosphorylated PLB
        D(iup_f_plb) ~
        0.001 * (
            c132 * pka_cyt_C * (1.0 - iup_f_plb) / (c134 + 1.0 - iup_f_plb) -
            c133 * PP1f_cyt * iup_f_plb / (c135 + iup_f_plb)
        )
    # Fraction of phosphorylated Troponin
        D(f_tni) ~
        0.001 * (
            c147 * pka_cyt_C * (1.0 - f_tni) / (c149 + 1.0 - f_tni) -
            c148 * c40 * f_tni / (c150 + f_tni)
        )
    # Fraction of phosphorylated INa channels
        D(ina_f_ina) ~
        0.001 * (
            c130 * pka_cav_C * (1.0 - ina_f_ina) / (c128 + 1.0 - ina_f_ina) -
            c131 * c36 * ina_f_ina / (c129 + ina_f_ina)
        )
    # Fraction of phosphorylated INaK
        D(f_inak) ~
        0.001 * (
            c124 * pka_cav_C * (1.0 - f_inak) / (c126 + 1.0 - f_inak) -
            c125 * c36 * f_inak / (c127 + f_inak)
        )
    # Fraction of phosphorylated IKur channels
        D(f_ikur) ~
        0.001 * (
            c136 * pka_eca_C * (1.0 - f_ikur) / (c138 + 1.0 - f_ikur) -
            c137 * c35 * f_ikur / (c139 + f_ikur)
        )
    # Substrates with AKAP
    iks_sig_IKsp_dif ~ c146 - IKsp
    # Concentration of phosphorylated IKs channels
        D(IKsp) ~
        0.001 * (
            c140 * pka_eca_C * iks_sig_IKsp_dif / (c142 + iks_sig_IKsp_dif) -
            c141 * c35 * IKsp / (c143 + IKsp)
        )
    akap_sig_RyRp_dif ~ c162 - RyRp
        D(RyRp) ~
        0.001 * (
            c152 * pka_cav_C * akap_sig_RyRp_dif / (c154 + akap_sig_RyRp_dif) -
            c153 * c36 * RyRp / (c155 + RyRp)
        )
    akap_sig_ICaLp_dif ~ c164 - ICaLp
    # Concentration of phosphorylated L-type Calcium channels
        D(ICaLp) ~
        0.001 * (
            c157 * pka_cav_C * akap_sig_ICaLp_dif / (c159 + akap_sig_ICaLp_dif) -
            c158 * c36 * ICaLp / (c160 + ICaLp)
        )
    end
end
