# This file was auto-generated by scripts/generate_model.jl
# Direct 1:1 translation from references/julia/signaling.jl

using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D

@mtkmodel GongBetaAdrenergic begin
    @structural_parameters begin
        iso_conc = 0.0
        radiusmultiplier = 1.0

        # Cell geometry
        ibmx = 0.0
        length = 0.01
        cell_pi = 3.14159265358979312e00
        radius = 0.0011 * radiusmultiplier
        volume = 1000.0 * cell_pi * radius * radius * length

        # PKA parameters
        PKA_tot = 0.5
        f_cav = 0.0388
        f_eca = 0.1
        f_cyt = 1.0 - f_cav - f_eca

        PKI_tot = 0.2 * PKA_tot
        f_pki_cav = f_cav
        f_pki_eca = f_eca
        f_pki_cyt = 1.0 - f_pki_cav - f_pki_eca

        K_pki = 0.01 / 50.0

        pka_cav_K1 = 2.4984
        pka_cav_K2 = 11.359
        pka_cav_K3 = 0.3755

        pka_eca_K1 = pka_cav_K1
        pka_eca_K2 = pka_cav_K2
        pka_eca_K3 = pka_cav_K3

        pka_cyt_K1 = 0.1088
        pka_cyt_K2 = 0.4612
        pka_cyt_K3 = 0.3755

        # PP1 parameters
        f = 0.3

        # PDE parameters
        PDE2_tot = 0.029268
        f_pde2_cav = 0.16957
        f_pde2_eca = 2.12570000000000006e-04
        f_pde2_cyt = 1.0 - f_pde2_cav - f_pde2_eca
        f_pde2_part = f_pde2_cav + f_pde2_eca
        f_pde_part = 0.2
        f_pde4_part = 0.125
        f_pde4_cav = 0.12481
        f_pde4_eca = f_pde4_part - f_pde4_cav
        f_pde4_cyt = 1.0 - f_pde4_part

        KmIbmxPde2 = 21.58
        h_ibmx_pde2 = 1.167
        h_ibmx_pde3 = 0.7629
        h_ibmx_pde4 = 0.9024
        KmIbmxPde3 = 2.642
        KmIbmxPde4 = 11.89

        KPDEp = 0.52218
        ff_pde3_cyt = 0.35
        r_pde34_frac = 3.71
        r_pde3_cyt = ff_pde3_cyt / (1.0 - ff_pde3_cyt)

        pde_PDE3_tot_alpha = r_pde3_cyt * (f_pde4_part * (1.0 + r_pde34_frac - r_pde34_frac * f_pde2_part - f_pde_part) + f_pde2_part * (f_pde_part - 1.0)) + r_pde34_frac * f_pde4_part * (f_pde_part - f_pde2_part)
        pde_PDE3_tot_beta = f_pde4_part * (1.0 + r_pde34_frac + f_pde_part * (r_pde3_cyt - r_pde34_frac)) - f_pde_part * (1.0 + r_pde3_cyt)

        PDE3_tot = pde_PDE3_tot_alpha / pde_PDE3_tot_beta * PDE2_tot
        PDE4_tot = ((f_pde_part - f_pde2_part) * PDE2_tot + f_pde_part * PDE3_tot) / ((1.0 + r_pde34_frac) * f_pde4_part - f_pde_part)

        ibmx_h2 = ibmx^h_ibmx_pde2
        ibmx_h3 = ibmx^h_ibmx_pde3
        ibmx_h4 = ibmx^h_ibmx_pde4

        ibmx2 = (1.0 - ibmx_h2 / (KmIbmxPde2 + ibmx_h2)) * PDE2_tot
        ibmx3 = (1.0 - ibmx_h3 / (KmIbmxPde3 + ibmx_h3)) * PDE3_tot
        ibmx4 = (1.0 - ibmx_h4 / (KmIbmxPde4 + ibmx_h4)) * PDE4_tot

        f_pde3_cav = r_pde34_frac * f_pde4_part * PDE4_tot / PDE3_tot
        f_pde3_cyt = 1.0 - f_pde3_cav

        # Receptor and G-protein parameters
        beta_R_b1_tot = 0.85 * 0.025
        beta_R_b2_tot = 0.15 * 0.025

        f_Rb1_cav = 0.081161
        f_Rb1_eca = 0.48744
        f_Rb1_cyt = 1.0 - f_Rb1_cav - f_Rb1_eca

        f_Rb2_cav = 0.85
        f_Rb2_eca = 1.0 - f_Rb2_cav

        rate_bds = 0.35

        # AC parameters
        ATP = 5000.0
        KmATP = 315.0
        AC_tot = 3.0 * beta_R_b1_tot
        f_AC47_eca = 0.16479
        f_AC56_cav = 0.087459
        f_AC56_AC47 = 1.0 / (1.0 + 0.35)

        # Substrate phosphorylation parameters
        # IKs AKAP parameters
        M = 0.01
        iks_sig_L = 0.0001
        iks_sig_K = 0.01
        Yotiao = 0.025

        # RyR and ICaL AKAP parameters
        RyR_akap = 0.125
        Mr = 0.01
        Lr = 0.0001
        Kr = 0.01

        ICaL_akap = 0.025
        Mi = 0.01
        Li = 0.0001
        Ki = 0.01
    end

    @parameters begin
        # c1-c7: Volume parameters
        c1 = iso_conc
        c2 = 0.02 * volume
        c3 = 0.04 * volume
        c4 = volume * 0.678
        c5 = volume / c2
        c6 = volume / c3
        c7 = volume / c4

        # c8-c10: cAMP diffusion rates
        c8 = 5e-15 * 1000000.0
        c9 = 7.5e-14 * 1000000.0
        c10 = 9e-15 * 1000000.0

        # c11-c30: PKA parameters
        c11 = f_eca * PKA_tot * c6
        c12 = f_cav * PKA_tot * c5
        c13 = f_cyt * PKA_tot * c7
        c14 = f_pki_cav * PKI_tot * c5
        c15 = f_pki_eca * PKI_tot * c6
        c16 = f_pki_cyt * PKI_tot * c7
        c17 = 50.0
        c18 = c17 * K_pki
        c19 = 100.0
        c20 = 100.0
        c21 = 100.0
        c22 = c19 * pka_cav_K1
        c23 = c20 * pka_cav_K2
        c24 = c21 * pka_cav_K3
        c25 = c19 * pka_eca_K1
        c26 = c20 * pka_eca_K2
        c27 = c21 * pka_eca_K3
        c28 = c19 * pka_cyt_K1
        c29 = c20 * pka_cyt_K2
        c30 = c21 * pka_cyt_K3

        # c31-c45: PP1 and PDE parameters
        c31 = 0.010145
        c32 = 0.0035731
        c33 = 0.001469
        c34 = 1.9526e-5
        c35 = 0.1
        c36 = 0.25
        c37 = 0.2
        c38 = 0.001
        c39 = f / (1.0 - f) * c38 + f * c37
        c40 = 1.0
        c41 = 20.0
        c42 = 2.5
        c43 = 4.0
        c44 = 50.0
        c45 = 0.8

        # c46-c57: PDE concentrations
        c46 = 1.4
        c47 = 3.0
        c48 = 0.0196
        c49 = KPDEp * c48
        c50 = ibmx2 * f_pde2_cav * c5
        c51 = ibmx2 * f_pde2_eca * c6
        c52 = ibmx2 * f_pde2_cyt * c7
        c53 = ibmx3 * f_pde3_cav * c5
        c54 = ibmx3 * f_pde3_cyt * c7
        c55 = ibmx4 * f_pde4_cav * c5
        c56 = ibmx4 * f_pde4_eca * c6
        c57 = ibmx4 * f_pde4_cyt * c7

        # c58-c106: Receptor and G-protein parameters
        c58 = 224.0 * beta_R_b1_tot
        c59 = 0.5
        c60 = 0.5664
        c61 = 0.0011071
        c62 = 1.0 - c61 - c60
        c63 = 0.85
        c64 = 1.0 - c63
        c65 = 0.567
        c66 = 2.449
        c67 = 0.062
        c68 = 1.053
        c69 = 0.012
        c70 = 1.6655
        c71 = 1.8463
        c72 = 1.053
        c73 = 0.1
        c74 = 4.9054
        c75 = 0.25945
        c76 = 4.0
        c77 = 0.05
        c78 = 0.8
        c79 = c78
        c80 = 1210.0
        c81 = c80
        c82 = rate_bds * 0.0009833
        c83 = rate_bds * 0.00133
        c84 = rate_bds * 0.0065
        c85 = 0.15629 * c84
        c86 = 1.0
        c87 = f_Rb1_cav * beta_R_b1_tot * c5
        c88 = 1.0
        c89 = f_Rb2_cav * beta_R_b2_tot * c5
        c90 = (c73 + c1) * (c68 + c1) / c68
        c91 = c71 * c69 * c65 * (c67 + c1) * (c72 + c1)
        c92 = c65 * c72 * (c67 + c1) * (c69 + c1)
        c93 = c66 * c71 * c67 * c69 * (c65 + c1) * (c72 + c1)
        c94 = c66 * c67 * c72 * (c69 + c1) * (c65 + c1)
        c95 = 1.0
        c96 = 1.0
        c97 = f_Rb2_eca * beta_R_b2_tot * c6
        c98 = f_Rb1_eca * beta_R_b1_tot * c6
        c99 = (c73 + c1) * (c68 + c1) / c68
        c100 = c66 * c67 * c72 * (c69 + c1) * (c65 + c1)
        c101 = c66 * c71 * c67 * c69 * (c65 + c1) * (c72 + c1)
        c102 = c65 * c72 * (c67 + c1) * (c69 + c1)
        c103 = c71 * c69 * c65 * (c67 + c1) * (c72 + c1)
        c104 = f_Rb1_cyt * beta_R_b1_tot * c7
        c105 = 1.0
        c106 = (c67 + c1) * (c65 + c1) / c65

        # c107-c123: AC parameters
        c107 = 1.0043
        c108 = 1.3574
        c109 = 0.6623
        c110 = 0.031544
        c111 = 0.0852
        c112 = 0.0465
        c113 = 0.4824
        c114 = 0.03135
        c115 = 0.037696
        c116 = 3.3757
        c117 = 41.32
        c118 = 0.8569
        c119 = (1.0 - f_AC47_eca) * (1.0 - f_AC56_AC47) * AC_tot * c7
        c120 = f_AC56_cav * f_AC56_AC47 * AC_tot * c5
        c121 = ATP / (KmATP + ATP)
        c122 = f_AC47_eca * (1.0 - f_AC56_AC47) * AC_tot * c6
        c123 = (1.0 - f_AC56_cav) * f_AC56_AC47 * AC_tot * c7

        # c124-c144: Substrate phosphorylation parameters
        c124 = 0.015265
        c125 = 0.092455
        c126 = 0.0011001
        c127 = 5.7392
        c128 = 0.10988
        c129 = 7.8605
        c130 = 0.01368
        c131 = 0.052811
        c132 = 0.11348
        c133 = 0.48302
        c134 = 9.88539999999999992e-04
        c135 = 0.80737
        c136 = 0.069537
        c137 = 0.317
        c138 = 0.27623
        c139 = 0.002331
        c140 = 0.16305
        c141 = 1.0542
        c142 = 9.97940000000000003e-05
        c143 = 1.11470000000000002e-04
        c144 = 0.025

        # c145-c146: IKs AKAP-bound concentrations
        iks_sig_PKAf_sum = 1.0 + (Yotiao - c11) / M
        iks_sig_PKAf = M / 2.0 * (sqrt(iks_sig_PKAf_sum^2.0 + 4.0 * c11 / M) - iks_sig_PKAf_sum)
        iks_sig_PP1f_eca_sum = 1.0 + (Yotiao - c35) / iks_sig_K
        PP1f_eca = iks_sig_K / 2.0 * (sqrt(iks_sig_PP1f_eca_sum^2.0 + 4.0 * c35 / iks_sig_K) - iks_sig_PP1f_eca_sum)
        iks_sig_IKsf_sum = 1.0 + (Yotiao - c144) / iks_sig_L
        IKsf = iks_sig_L / 2.0 * (sqrt(iks_sig_IKsf_sum^2.0 + 4.0 * c144 / iks_sig_L) - iks_sig_IKsf_sum)
        Yotiaof = (Yotiao - c144 + IKsf) / ((1.0 + PP1f_eca / iks_sig_K) * (1.0 + iks_sig_PKAf / M))
        c145 = IKsf * Yotiaof * iks_sig_PKAf / (iks_sig_L * M)
        c146 = c145 * PP1f_eca / iks_sig_K

        # c147-c160: More substrate parameters
        c147 = 0.10408
        c148 = 0.052633
        c149 = 2.71430000000000008e-05
        c150 = 0.26714
        c151 = 0.125
        c152 = 0.0025548
        c153 = 0.0038257
        c154 = 6.62979999999999944e-05
        c155 = 0.043003
        c156 = 0.025
        c157 = 5.10090000000000044e-04
        c158 = 0.0006903
        c159 = 1.27019999999999993e-06
        c160 = 0.0063064

        # c161-c164: RyR and ICaL AKAP-bound concentrations
        akap_sig_RyRf_sum = 1.0 + (RyR_akap - c151) / Lr
        RyRf = Lr / 2.0 * (sqrt(akap_sig_RyRf_sum^2.0 + 4.0 * c151 / Lr) - akap_sig_RyRf_sum)
        akap_sig_ICaLf_sum = 1.0 + (ICaL_akap - c156) / Li
        ICaLf = Li / 2.0 * (sqrt(akap_sig_ICaLf_sum^2.0 + 4.0 * c156 / Li) - akap_sig_ICaLf_sum)

        akap_sig_PP1f_cav_b = ICaL_akap + RyR_akap + Ki + Kr - c36
        akap_sig_PP1f_cav_c = ICaL_akap * Kr + RyR_akap * Ki + Ki * Kr - c36 * (Ki + Kr)
        akap_sig_PP1f_cav_d = c36 * Ki * Kr
        akap_sig_PP1f_cav_rr = -akap_sig_PP1f_cav_d / 27.0 * akap_sig_PP1f_cav_b^3.0 - akap_sig_PP1f_cav_b * akap_sig_PP1f_cav_b * akap_sig_PP1f_cav_c * akap_sig_PP1f_cav_c / 108.0 + akap_sig_PP1f_cav_b * akap_sig_PP1f_cav_c * akap_sig_PP1f_cav_d / 6.0 + akap_sig_PP1f_cav_c^3.0 / 27.0 + akap_sig_PP1f_cav_d * akap_sig_PP1f_cav_d / 4.0
        akap_sig_PP1f_cav_yi = sqrt(max(0.0, -akap_sig_PP1f_cav_rr))
        akap_sig_PP1f_cav_yr = sqrt(max(0.0, akap_sig_PP1f_cav_rr)) + akap_sig_PP1f_cav_d / 2.0 + akap_sig_PP1f_cav_b * akap_sig_PP1f_cav_c / 6.0 - akap_sig_PP1f_cav_b^3.0 / 27.0
        akap_sig_PP1f_cav_mag = (akap_sig_PP1f_cav_yr * akap_sig_PP1f_cav_yr + akap_sig_PP1f_cav_yi * akap_sig_PP1f_cav_yi)^(1.0 / 6.0)
        akap_sig_PP1f_cav_arg = atan(akap_sig_PP1f_cav_yi / akap_sig_PP1f_cav_yr) / 3.0
        akap_sig_PP1f_cav_x = (akap_sig_PP1f_cav_c / 3.0 - akap_sig_PP1f_cav_b * akap_sig_PP1f_cav_b / 9.0) / (akap_sig_PP1f_cav_mag * akap_sig_PP1f_cav_mag)
        PP1f_cav = akap_sig_PP1f_cav_mag * cos(akap_sig_PP1f_cav_arg) * (1.0 - akap_sig_PP1f_cav_x) - akap_sig_PP1f_cav_b / 3.0

        akap_sig_PKAf_d = c12 * Mi * Mr
        akap_sig_PKAf_b = ICaL_akap + RyR_akap + Mi + Mr - c12
        akap_sig_PKAf_c = ICaL_akap * Mr + RyR_akap * Mi + Mi * Mr - c12 * (Mi + Mr)
        akap_sig_PKAf_rr = -akap_sig_PKAf_d / 27.0 * akap_sig_PKAf_b^3.0 - akap_sig_PKAf_b * akap_sig_PKAf_b * akap_sig_PKAf_c * akap_sig_PKAf_c / 108.0 + akap_sig_PKAf_b * akap_sig_PKAf_c * akap_sig_PKAf_d / 6.0 + akap_sig_PKAf_c^3.0 / 27.0 + akap_sig_PKAf_d * akap_sig_PKAf_d / 4.0
        akap_sig_PKAf_yr = sqrt(max(0.0, akap_sig_PKAf_rr)) + akap_sig_PKAf_d / 2.0 + akap_sig_PKAf_b * akap_sig_PKAf_c / 6.0 - akap_sig_PKAf_b^3.0 / 27.0
        akap_sig_PKAf_yi = sqrt(max(0.0, -akap_sig_PKAf_rr))
        akap_sig_PKAf_mag = (akap_sig_PKAf_yr * akap_sig_PKAf_yr + akap_sig_PKAf_yi * akap_sig_PKAf_yi)^(1.0 / 6.0)
        akap_sig_PKAf_arg = atan(akap_sig_PKAf_yi / akap_sig_PKAf_yr) / 3.0
        akap_sig_PKAf_x = (akap_sig_PKAf_c / 3.0 - akap_sig_PKAf_b * akap_sig_PKAf_b / 9.0) / (akap_sig_PKAf_mag * akap_sig_PKAf_mag)
        akap_sig_PKAf = akap_sig_PKAf_mag * cos(akap_sig_PKAf_arg) * (1.0 - akap_sig_PKAf_x) - akap_sig_PKAf_b / 3.0

        RyR_akapf = (RyR_akap - c151 + RyRf) / ((PP1f_cav / Kr + 1.0) * (akap_sig_PKAf / Mr + 1.0))
        ICaL_akapf = (ICaL_akap - c156 + ICaLf) / ((PP1f_cav / Ki + 1.0) * (akap_sig_PKAf / Mi + 1.0))
        c161 = RyRf * RyR_akapf * akap_sig_PKAf / (Lr * Mr)
        c162 = c161 * PP1f_cav / Kr
        c163 = ICaLf * ICaL_akapf * akap_sig_PKAf / (Li * Mi)
        c164 = c163 * PP1f_cav / Ki

        # c165-c167: Effective phosphorylation fractions
        c165 = 0.0329 + c161 / c151
        c166 = 0.0269 + c163 / c156
        c167 = 0.0306 + c145 / c144
    end

    @variables begin
        # State variables with initial conditions
        beta_cav_Gs_aGTP(t) = 0.00685533455220118
        beta_eca_Gs_aGTP(t) = 0.0184630401160325
        beta_cyt_Gs_aGTP(t) = 0.000731426797266862
        beta_cav_Gs_bg(t) = 0.0074626834509494
        beta_eca_Gs_bg(t) = 0.0191020788696145
        beta_cyt_Gs_bg(t) = 0.00115141961261304
        beta_cav_Gs_aGDP(t) = 0.000607348898749425
        beta_eca_Gs_aGDP(t) = 0.000639038753581265
        beta_cyt_Gs_aGDP(t) = 0.00041999281534611
        cAMP_cav(t) = 0.344257659177271
        cAMP_eca(t) = 9.62262190945345
        cAMP_cyt(t) = 0.474028267773051
        beta_cav_Rb1_pka_tot(t) = 0.0148474493496437
        beta_eca_Rb1_pka_tot(t) = 0.2030159857254
        beta_cyt_Rb1_pka_tot(t) = 0.00944459882156118
        beta_cav_Rb1_grk_tot(t) = 1.76916170568022e-10
        beta_eca_Rb1_grk_tot(t) = 8.36801924219387e-10
        beta_cyt_Rb1_grk_tot(t) = 5.01719476559362e-11
        pka_cav_ARC(t) = 0.0898875954193269
        pka_cav_A2RC(t) = 0.00272422687231002
        pka_cav_A2R(t) = 0.225041998219388
        pka_cav_C(t) = 0.032238122010232
        pka_cav_PKIC(t) = 0.192803876209063
        pka_eca_ARC(t) = 0.205457169881723
        pka_eca_A2RC(t) = 0.174050238959555
        pka_eca_A2R(t) = 0.817148066343192
        pka_eca_C(t) = 0.567236181979005
        pka_eca_PKIC(t) = 0.249911884364108
        pka_cyt_ARC(t) = 0.0646981828366729
        pka_cyt_A2RC(t) = 0.0664977613514265
        pka_cyt_A2R(t) = 0.489057632872032
        pka_cyt_C(t) = 0.362107101574369
        pka_cyt_PKIC(t) = 0.126950531297531
        PDE3_P_cav(t) = 0.02339549924788
        PDE3_P_cyt(t) = 0.0128401592747216
        PDE4_P_cav(t) = 0.00629647926927854
        PDE4_P_eca(t) = 4.29166115483698e-5
        PDE4_P_cyt(t) = 0.00917030613498568
        inhib1_p(t) = 0.0123536190564101
        ICaLp(t) = 0.000664158274421826
        IKsp(t) = 0.000765842738691197
        iup_f_plb(t) = 0.666165471397222
        f_tni(t) = 0.673477756497978
        ina_f_ina(t) = 0.236980176272067
        f_inak(t) = 0.124710628782511
        RyRp(t) = 0.00404925913372347
        f_ikur(t) = 0.0589106047787742
        beta_cav_Rb2_pka_tot(t) = 0.0274407333314977
        beta_cav_Rb2_grk_tot(t) = 6.32124571143896e-10
        beta_cav_Gi_aGTP(t) = 0.00159025206300466
        beta_cav_Gi_bg(t) = 0.00209267447556971
        beta_cav_Gi_aGDP(t) = 0.000502422412564797
        beta_eca_Rb2_pka_tot(t) = 0.0110248493074472
        beta_eca_Rb2_grk_tot(t) = 8.04005829146876e-11
        beta_eca_Gi_aGTP(t) = 0.000364313646402573
        beta_eca_Gi_bg(t) = 0.000705654325530757
        beta_eca_Gi_aGDP(t) = 0.000341340679127998

        # Intermediate variables
        beta_cav_Rb1_np_tot(t)
        beta_cav_Rb2_np_tot(t)
        beta_cav_Gi_abg(t)
        beta_cav_Gs_abg(t)
        beta_cav_Gs_f_d(t)
        beta_cav_Gs_f_b(t)
        beta_cav_Gs_f_c(t)
        beta_cav_Gs_f_rr(t)
        beta_cav_Gs_f_yr(t)
        beta_cav_Gs_f_yi(t)
        beta_cav_Gs_f_mag(t)
        beta_cav_Gs_f_arg(t)
        beta_cav_Gs_f_x(t)
        beta_cav_Gs_f_r(t)
        beta_cav_Gs_f_i(t)
        beta_cav_Gs_f(t)
        beta_cav_Rb1_f(t)
        beta_cav_LRb1(t)
        beta_cav_LRb1Gs(t)
        beta_cav_Rb2_f(t)
        beta_cav_LRb2(t)
        beta_cav_Rb2Gs(t)
        beta_cav_Rb1Gs(t)
        beta_cav_LRb2Gs(t)
        beta_eca_Gs_abg(t)
        beta_eca_Rb2_np_tot(t)
        beta_eca_Rb1_np_tot(t)
        beta_eca_Gs_f_d(t)
        beta_eca_Gs_f_c(t)
        beta_eca_Gs_f_b(t)
        beta_eca_Gs_f_rr(t)
        beta_eca_Gs_f_yi(t)
        beta_eca_Gs_f_yr(t)
        beta_eca_Gs_f_mag(t)
        beta_eca_Gs_f_arg(t)
        beta_eca_Gs_f_x(t)
        beta_eca_Gs_f_i(t)
        beta_eca_Gs_f_r(t)
        beta_eca_Gs_f(t)
        beta_eca_Rb1_f(t)
        beta_eca_Rb2_f(t)
        beta_eca_LRb1(t)
        beta_eca_LRb2(t)
        beta_eca_LRb2Gs(t)
        beta_eca_LRb1Gs(t)
        beta_eca_Rb2Gs(t)
        beta_eca_Rb1Gs(t)
        beta_eca_RGs_tot(t)
        beta_eca_LRGs_tot(t)
        beta_eca_Gi_abg(t)
        beta_eca_Rb2_pka_f_c(t)
        beta_eca_Rb2_pka_f_b(t)
        beta_eca_Rb2_pka_f(t)
        beta_cyt_Gs_abg(t)
        beta_cyt_Rb1_np_tot(t)
        beta_cyt_Rb1_np_f_b(t)
        beta_cyt_Rb1_np_f_c(t)
        Rb1_np_f(t)
        beta_cyt_Gs_f(t)
        LRb1_np(t)
        LRb1Gs_np(t)
        Rb1Gs_np(t)
        beta_cav_RGs_tot(t)
        beta_cav_LRGs_tot(t)
        beta_cav_Rb2_pka_f_c(t)
        beta_cav_Rb2_pka_f_b(t)
        beta_cav_Rb2_pka_f(t)
        beta_cav_Gi_f(t)
        beta_cav_Rb2Gi(t)
        beta_cav_LRb2Gi(t)
        beta_eca_Gi_f(t)
        beta_eca_Rb2Gi(t)
        beta_eca_LRb2Gi(t)
        pka_cav_RCf(t)
        pka_eca_RCf(t)
        pka_eca_dcAMP(t)
        pka_cyt_RCf(t)
        pka_cav_dcAMP(t)
        pka_cyt_dcAMP(t)
        dcAMP_PDE2_cyt(t)
        dcAMP_PDE2_eca(t)
        dcAMP_PDE2_cav(t)
        dcAMP_PDE3_cav(t)
        dcAMP_PDE4_cyt(t)
        dcAMP_PDE4_eca(t)
        dcAMP_PDE4_cav(t)
        dcAMP_PDE3_cyt(t)
        camp_cAMP_cyt_pde(t)
        camp_cAMP_cyt_j1(t)
        camp_cAMP_cyt_j2(t)
        camp_cAMP_eca_pde(t)
        camp_cAMP_eca_j2(t)
        camp_cAMP_eca_j1(t)
        camp_cAMP_cav_pde(t)
        camp_cAMP_cav_j2(t)
        camp_cAMP_cav_j1(t)
        ac_kAC47_cyt_gsa(t)
        kAC47_cyt(t)
        ac_kAC56_cav_gsa(t)
        gsi(t)
        kAC56_cav(t)
        ac_kAC47_eca_gsa(t)
        kAC47_eca(t)
        ac_kAC56_cyt_gsa(t)
        kAC56_cyt(t)
        dcAMP_AC47_cyt(t)
        dcAMP_AC56_cyt(t)
        dcAMP_AC56_cav(t)
        dcAMP_AC47_eca(t)
        pp1_PP1f_cyt_sum(t)
        PP1f_cyt(t)
        di(t)
        iks_sig_IKsp_dif(t)
        akap_sig_RyRp_dif(t)
        akap_sig_ICaLp_dif(t)
    end

    @equations begin
    # CAVEOLAR %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    # Total concentration of non-phosphorylated B1AR in the caveolar subspace
    beta_cav_Rb1_np_tot ~ c87 - beta_cav_Rb1_pka_tot - beta_cav_Rb1_grk_tot
    # Total concentration of non-phosphorylated B2AR in the caveolar subspace
    beta_cav_Rb2_np_tot ~ c89 - beta_cav_Rb2_pka_tot - beta_cav_Rb2_grk_tot
    # Concentration of Gi holoenzyme in the caveolar subspace
    beta_cav_Gi_abg ~ c63 * c59 * c5 - beta_cav_Gi_aGTP - beta_cav_Gi_aGDP
    # Concentration of Gs holoenzyme in the caveolar subspace
    beta_cav_Gs_abg ~ c61 * c58 * c5 - beta_cav_Gs_aGTP - beta_cav_Gs_aGDP
    beta_cav_Gs_f_d ~ beta_cav_Gs_abg * c93 / c92
    beta_cav_Gs_f_b ~
        (c94 + c91) / c92 + beta_cav_Rb1_np_tot + beta_cav_Rb2_np_tot -
        beta_cav_Gs_abg
    beta_cav_Gs_f_c ~
        (
            c91 * (beta_cav_Rb1_np_tot - beta_cav_Gs_abg) +
            c94 * (beta_cav_Rb2_np_tot - beta_cav_Gs_abg) +
            c93
        ) / c92
    beta_cav_Gs_f_rr ~ (
        -beta_cav_Gs_f_d / 27.0 * beta_cav_Gs_f_b^3.0 -
        beta_cav_Gs_f_b * beta_cav_Gs_f_b * beta_cav_Gs_f_c * beta_cav_Gs_f_c / 108.0 +
        beta_cav_Gs_f_b * beta_cav_Gs_f_c * beta_cav_Gs_f_d / 6.0 +
        beta_cav_Gs_f_c^3.0 / 27.0 +
        beta_cav_Gs_f_d * beta_cav_Gs_f_d / 4.0
    )
    beta_cav_Gs_f_yr ~ (
        sqrt(max(0.0, beta_cav_Gs_f_rr)) +
        beta_cav_Gs_f_d / 2.0 +
        beta_cav_Gs_f_b * beta_cav_Gs_f_c / 6.0 - beta_cav_Gs_f_b^3.0 / 27.0
    )
    beta_cav_Gs_f_yi ~ sqrt(max(0.0, -beta_cav_Gs_f_rr))
    beta_cav_Gs_f_mag ~
        (
            beta_cav_Gs_f_yr * beta_cav_Gs_f_yr + beta_cav_Gs_f_yi * beta_cav_Gs_f_yi
        )^(1.0 / 6.0)
    beta_cav_Gs_f_arg ~ atan(beta_cav_Gs_f_yi / beta_cav_Gs_f_yr) / 3.0
    beta_cav_Gs_f_x ~
        (beta_cav_Gs_f_c / 3.0 - beta_cav_Gs_f_b * beta_cav_Gs_f_b / 9.0) /
        (beta_cav_Gs_f_mag * beta_cav_Gs_f_mag)
    beta_cav_Gs_f_r ~
        beta_cav_Gs_f_mag * cos(beta_cav_Gs_f_arg) * (1.0 - beta_cav_Gs_f_x) -
        beta_cav_Gs_f_b / 3.0
    beta_cav_Gs_f_i ~ beta_cav_Gs_f_mag * sin(beta_cav_Gs_f_arg) * (1.0 + beta_cav_Gs_f_x)
    # Concentration of free Gs in the caveolar subspace
    beta_cav_Gs_f ~ sqrt(beta_cav_Gs_f_r * beta_cav_Gs_f_r + beta_cav_Gs_f_i * beta_cav_Gs_f_i)
    # Concentration of free non-phosphorylated beta1AR in caveolar subspace
    beta_cav_Rb1_f ~
        beta_cav_Rb1_np_tot /
        (1.0 + c1 / c65 + beta_cav_Gs_f * (c67 + c1) / (c66 * c67))
    # Concentration of non-phosphorylated Ligand / Receptor1 complexes in caveolar subspace
    beta_cav_LRb1 ~ c1 * beta_cav_Rb1_f / c65
    # Concentration of non-phosphorylated Ligand /
    # Receptor1 / G-protein complexes in caveolar subspace
    beta_cav_LRb1Gs ~ c1 * beta_cav_Rb1_f * beta_cav_Gs_f / (c66 * c67)
    # Concentration of free non-phosphorylated beta2AR in caveolar subspace
    beta_cav_Rb2_f ~
        beta_cav_Rb2_np_tot /
        (1.0 + c1 / c72 + beta_cav_Gs_f * (c69 + c1) / (c71 * c69))
    # Concentration of non-phosphorylated Ligand /
    # Receptor2 complexes in caveolar subspace
    beta_cav_LRb2 ~ c1 * beta_cav_Rb2_f / c72
    # Concentration of non-phosphorylated Receptor2 /
    # G-protein complexes in caveolar subspace
    beta_cav_Rb2Gs ~ beta_cav_Rb2_f * beta_cav_Gs_f / c71
    # Concentration of non-phosphorylated Receptor1 /
    # G-protein complexes in caveolar subspace
    beta_cav_Rb1Gs ~ beta_cav_Rb1_f * beta_cav_Gs_f / c66
    # Concentration of non-phosphorylated Ligand /
    # Receptor2 / G-protein complexes in caveolar subspace
    beta_cav_LRb2Gs ~ c1 * beta_cav_Rb2_f * beta_cav_Gs_f / (c71 * c69)
    # Concentration of total PKA-phosphorylated beta1 receptors
        D(beta_cav_Rb1_pka_tot) ~
        0.001 * (c84 * pka_cav_C * beta_cav_Rb1_np_tot - c85 * beta_cav_Rb1_pka_tot)
    # Concentration of total GRK-phosphorylated beta1 receptors
        D(beta_cav_Rb1_grk_tot) ~
        0.001 *
        (c83 * c86 * (beta_cav_LRb1 + beta_cav_LRb1Gs) - c82 * beta_cav_Rb1_grk_tot)
    # Concentration of total PKA-phosphorylated beta2 receptors
        D(beta_cav_Rb2_pka_tot) ~
        0.001 * (c84 * pka_cav_C * beta_cav_Rb2_np_tot - c85 * beta_cav_Rb2_pka_tot)
    # Concentration of total GRK-phosphorylated beta2 receptors
        D(beta_cav_Rb2_grk_tot) ~
        0.001 *
        (c83 * c86 * (beta_cav_LRb2 + beta_cav_LRb2Gs) - c82 * beta_cav_Rb2_grk_tot)
    # EXTRACAVEOLAR %%%%%%%%%%%%%%%%%%
    #
    # beta_eca
    #
    # Concentration of Gs holoenzyme in the extracaveolar space
    beta_eca_Gs_abg ~ c60 * c58 * c6 - beta_eca_Gs_aGTP - beta_eca_Gs_aGDP
    # Total concentration of non-phosphorylated B2AR in the extracaveolar space
    beta_eca_Rb2_np_tot ~ c97 - beta_eca_Rb2_pka_tot - beta_eca_Rb2_grk_tot
    # Total concentration of non-phosphorylated B1AR in the extracaveolar space
    beta_eca_Rb1_np_tot ~ c98 - beta_eca_Rb1_pka_tot - beta_eca_Rb1_grk_tot
    beta_eca_Gs_f_d ~ beta_eca_Gs_abg * c101 / c102
    beta_eca_Gs_f_c ~
        (
            c103 * (beta_eca_Rb1_np_tot - beta_eca_Gs_abg) +
            c100 * (beta_eca_Rb2_np_tot - beta_eca_Gs_abg) +
            c101
        ) / c102
    beta_eca_Gs_f_b ~
        (c100 + c103) / c102 + beta_eca_Rb1_np_tot + beta_eca_Rb2_np_tot -
        beta_eca_Gs_abg
    beta_eca_Gs_f_rr ~ (
        -beta_eca_Gs_f_d / 27.0 * beta_eca_Gs_f_b^3.0 -
        beta_eca_Gs_f_b * beta_eca_Gs_f_b * beta_eca_Gs_f_c * beta_eca_Gs_f_c / 108.0 +
        beta_eca_Gs_f_b * beta_eca_Gs_f_c * beta_eca_Gs_f_d / 6.0 +
        beta_eca_Gs_f_c^3.0 / 27.0 +
        beta_eca_Gs_f_d * beta_eca_Gs_f_d / 4.0
    )
    beta_eca_Gs_f_yi ~ sqrt(max(0.0, -beta_eca_Gs_f_rr))
    beta_eca_Gs_f_yr ~ (
        sqrt(max(0.0, beta_eca_Gs_f_rr)) +
        beta_eca_Gs_f_d / 2.0 +
        beta_eca_Gs_f_b * beta_eca_Gs_f_c / 6.0 - beta_eca_Gs_f_b^3.0 / 27.0
    )
    beta_eca_Gs_f_mag ~
        (
            beta_eca_Gs_f_yr * beta_eca_Gs_f_yr + beta_eca_Gs_f_yi * beta_eca_Gs_f_yi
        )^(1.0 / 6.0)
    beta_eca_Gs_f_arg ~ atan(beta_eca_Gs_f_yi / beta_eca_Gs_f_yr) / 3.0
    beta_eca_Gs_f_x ~
        (beta_eca_Gs_f_c / 3.0 - beta_eca_Gs_f_b * beta_eca_Gs_f_b / 9.0) /
        (beta_eca_Gs_f_mag * beta_eca_Gs_f_mag)
    beta_eca_Gs_f_i ~ beta_eca_Gs_f_mag * sin(beta_eca_Gs_f_arg) * (1.0 + beta_eca_Gs_f_x)
    beta_eca_Gs_f_r ~
        beta_eca_Gs_f_mag * cos(beta_eca_Gs_f_arg) * (1.0 - beta_eca_Gs_f_x) -
        beta_eca_Gs_f_b / 3.0
    # Concentration of free Gs in the caveolar subspace
    beta_eca_Gs_f ~ sqrt(beta_eca_Gs_f_r * beta_eca_Gs_f_r + beta_eca_Gs_f_i * beta_eca_Gs_f_i)
    # Concentration of free non-phosphorylated beta1AR in the extracaveolar space
    beta_eca_Rb1_f ~
        beta_eca_Rb1_np_tot /
        (1.0 + c1 / c65 + beta_eca_Gs_f * (c67 + c1) / (c66 * c67))
    # Concentration of free non-phosphorylated beta2AR in the extracaveolar space
    beta_eca_Rb2_f ~
        beta_eca_Rb2_np_tot /
        (1.0 + c1 / c72 + beta_eca_Gs_f * (c69 + c1) / (c71 * c69))
    # Concentration of non-phosphorylated Ligand / Receptor1 complexes in the extracaveolar space
    beta_eca_LRb1 ~ c1 * beta_eca_Rb1_f / c65
    # Concentration of non-phosphorylated Ligand / Receptor2 complexes in the extracaveolar space
    beta_eca_LRb2 ~ c1 * beta_eca_Rb2_f / c72
    # Concentration of non-phosphorylated Ligand /
    # Receptor2 / G-protein complexes in the extracaveolar space
    beta_eca_LRb2Gs ~ c1 * beta_eca_Rb2_f * beta_eca_Gs_f / (c71 * c69)
    # Concentration of non-phosphorylated Ligand /
    # Receptor1 / G-protein complexes in the extracaveolar space
    beta_eca_LRb1Gs ~ c1 * beta_eca_Rb1_f * beta_eca_Gs_f / (c66 * c67)
    # Concentration of non-phosphorylated Receptor2 / G-protein complexes in the extracaveolar space
    beta_eca_Rb2Gs ~ beta_eca_Rb2_f * beta_eca_Gs_f / c71
    # Concentration of non-phosphorylated Receptor1 / G-protein complexes in the extracaveolar space
    beta_eca_Rb1Gs ~ beta_eca_Rb1_f * beta_eca_Gs_f / c66
    beta_eca_RGs_tot ~ beta_eca_Rb1Gs + c96 * beta_eca_Rb2Gs
    beta_eca_LRGs_tot ~ beta_eca_LRb1Gs + c96 * beta_eca_LRb2Gs
    # Concentration of Gi holoenzyme in the extracaveolar space
    beta_eca_Gi_abg ~ c64 * c59 * c6 - beta_eca_Gi_aGTP - beta_eca_Gi_aGDP
    beta_eca_Rb2_pka_f_c ~ -beta_eca_Rb2_pka_tot * c70 * c73
    beta_eca_Rb2_pka_f_b ~ (
        beta_eca_Gi_abg * (c1 + c73) - beta_eca_Rb2_pka_tot * (c73 + c1) +
        c70 * c73 * (1.0 + c1 / c68)
    )
    # Concentration of free PKA-phosphorylated beta2AR in the extracaveolar space
    beta_eca_Rb2_pka_f ~
        (
            -beta_eca_Rb2_pka_f_b + sqrt(
                beta_eca_Rb2_pka_f_b * beta_eca_Rb2_pka_f_b -
                4.0 * c99 * beta_eca_Rb2_pka_f_c,
            )
        ) / (2.0 * c99)
    # Concentration of total PKA-phosphorylated beta1 receptors in the extracaveolar space
        D(beta_eca_Rb1_pka_tot) ~
        0.001 * (c84 * pka_eca_C * beta_eca_Rb1_np_tot - c85 * beta_eca_Rb1_pka_tot)
    # Concentration of total GRK-phosphorylated beta1 receptors in the extracaveolar space
        D(beta_eca_Rb1_grk_tot) ~
        0.001 *
        (c83 * c95 * (beta_eca_LRb1 + beta_eca_LRb1Gs) - c82 * beta_eca_Rb1_grk_tot)
    # Concentration of total PKA-phosphorylated beta2 receptors in the extracaveolar space
        D(beta_eca_Rb2_pka_tot) ~
        0.001 * (c84 * pka_eca_C * beta_eca_Rb2_np_tot - c85 * beta_eca_Rb2_pka_tot)
    # Concentration of total GRK-phosphorylated beta2 receptors in the extracaveolar space
        D(beta_eca_Rb2_grk_tot) ~
        0.001 *
        (c83 * c95 * (beta_eca_LRb2 + beta_eca_LRb2Gs) - c82 * beta_eca_Rb2_grk_tot)
    # CYTOPLASM %%%%%%%%%%%
    # Concentration of Gs holoenzyme in the cytoplasm
    beta_cyt_Gs_abg ~ c62 * c58 * c7 - beta_cyt_Gs_aGTP - beta_cyt_Gs_aGDP
    # Total concentration of non-phosphorylated beta-1 AR in the cytoplasm
    beta_cyt_Rb1_np_tot ~ c104 - beta_cyt_Rb1_pka_tot - beta_cyt_Rb1_grk_tot
    beta_cyt_Rb1_np_f_b ~ (
        beta_cyt_Gs_abg * (c67 + c1) - beta_cyt_Rb1_np_tot * (c67 + c1) +
        c66 * c67 * (1.0 + c1 / c65)
    )
    beta_cyt_Rb1_np_f_c ~ -beta_cyt_Rb1_np_tot * c67 * c66
    # Concentration of free non-phosphorylated beta-1 AR in the cytoplasm
    Rb1_np_f ~
        (
            -beta_cyt_Rb1_np_f_b + sqrt(
                beta_cyt_Rb1_np_f_b * beta_cyt_Rb1_np_f_b -
                4.0 * c106 * beta_cyt_Rb1_np_f_c,
            )
        ) / (2.0 * c106)
    # Concentration of free (non-complexed) Gi in the cytoplasm
    beta_cyt_Gs_f ~ beta_cyt_Gs_abg / (1.0 + Rb1_np_f / c66 * (1.0 + c1 / c67))
    # Concentration of non-phosphorylated ligand / beta-1 AR complexes in the cytoplasm
    LRb1_np ~ c1 * Rb1_np_f / c65
    # Concentration of non-phosphorylated ligand / beta-1 AR / Gs complexes in the cytoplasm
    LRb1Gs_np ~ c1 * Rb1_np_f * beta_cyt_Gs_f / (c66 * c67)
    # Concentration of non-phosphorylated beta-1 AR / Gs complexes in the cytoplasm
    Rb1Gs_np ~ beta_cyt_Gs_f * Rb1_np_f / c66
    # Concentration of total PKA-phosphorylated receptors in the cytoplasm
        D(beta_cyt_Rb1_pka_tot) ~
        0.001 * (c84 * pka_cyt_C * beta_cyt_Rb1_np_tot - c85 * beta_cyt_Rb1_pka_tot)
    # Concentration of total GRK-phosphorylated receptors in the cytoplasm
        D(beta_cyt_Rb1_grk_tot) ~ 0.001 * (c83 * c105 * (LRb1_np + LRb1Gs_np) - c82 * beta_cyt_Rb1_grk_tot)
    # function Mod_GprotAct() in the other version %%%
    beta_cav_RGs_tot ~ beta_cav_Rb1Gs + c88 * beta_cav_Rb2Gs
    beta_cav_LRGs_tot ~ beta_cav_LRb1Gs + c88 * beta_cav_LRb2Gs
    beta_cav_Rb2_pka_f_c ~ -beta_cav_Rb2_pka_tot * c70 * c73
    beta_cav_Rb2_pka_f_b ~ (
        beta_cav_Gi_abg * (c1 + c73) - beta_cav_Rb2_pka_tot * (c73 + c1) +
        c70 * c73 * (1.0 + c1 / c68)
    )
    # Concentration of free PKA-phosphorylated beta2AR in the caveolar subspace
    beta_cav_Rb2_pka_f ~
        (
            -beta_cav_Rb2_pka_f_b + sqrt(
                beta_cav_Rb2_pka_f_b * beta_cav_Rb2_pka_f_b -
                4.0 * c90 * beta_cav_Rb2_pka_f_c,
            )
        ) / (2.0 * c90)
    # Concentration of free (non-complexed) Gi in the caveolar subspace
    beta_cav_Gi_f ~
        beta_cav_Gi_abg / (1.0 + beta_cav_Rb2_pka_f / c70 * (1.0 + c1 / c73))
    # Concentration of PKA phosphorylated b2AR/Gi complexes in caveolar subspace
    beta_cav_Rb2Gi ~ beta_cav_Rb2_pka_f * beta_cav_Gi_f / c70
    # Concentration of PKA phosphorylated Ligand/b2AR/Gi complexes in caveolar subspace
    beta_cav_LRb2Gi ~ beta_cav_Rb2Gi * c1 / c73
    # Concentration of free (non-complexed) Gi in the extracaveolar space
    beta_eca_Gi_f ~
        beta_eca_Gi_abg / (1.0 + beta_eca_Rb2_pka_f / c70 * (1.0 + c1 / c73))
    # Concentration of PKA phosphorylated b2AR/Gi complexes in extracaveolar space
    beta_eca_Rb2Gi ~ beta_eca_Rb2_pka_f * beta_eca_Gi_f / c70
    # Concentration of PKA phosphorylated Ligand/b2AR/Gi complexes in extracaveolar space
    beta_eca_LRb2Gi ~ c1 / c73 * beta_eca_Rb2Gi
    # Concentration of active Gs alpha subunit in caveolar subspace (tri-phosphate)
        D(beta_cav_Gs_aGTP) ~
        0.001 *
        (c75 * beta_cav_RGs_tot + c74 * beta_cav_LRGs_tot - c78 * beta_cav_Gs_aGTP)
    # Concentration of active Gi alpha subunit in caveolar subspace
        D(beta_cav_Gi_aGTP) ~
        0.001 *
        (c77 * beta_cav_Rb2Gi + c76 * beta_cav_LRb2Gi - c79 * beta_cav_Gi_aGTP)
    # Concentration of active Gs alpha subunit in the extracaveolar space (tri-phosphate)
        D(beta_eca_Gs_aGTP) ~
        0.001 *
        (c75 * beta_eca_RGs_tot + c74 * beta_eca_LRGs_tot - c78 * beta_eca_Gs_aGTP)
    # Concentration of active Gi alpha subunit in the extracaveolar space
        D(beta_eca_Gi_aGTP) ~
        0.001 *
        (c77 * beta_eca_Rb2Gi + c76 * beta_eca_LRb2Gi - c79 * beta_eca_Gi_aGTP)
    # Concentration of active Gs alpha subunit in cytoplasm
        D(beta_cyt_Gs_aGTP) ~ 0.001 * (c75 * Rb1Gs_np + c74 * LRb1Gs_np - c78 * beta_cyt_Gs_aGTP)
    # Concentration of active Gs beta-gamma subunit in caveolar subspace
        D(beta_cav_Gs_bg) ~
        0.001 * (
            c75 * beta_cav_RGs_tot + c74 * beta_cav_LRGs_tot -
            c80 * beta_cav_Gs_bg * beta_cav_Gs_aGDP
        )
    # Concentration of active Gi beta-gamma subunit in caveolar subspace
        D(beta_cav_Gi_bg) ~
        0.001 * (
            c77 * beta_cav_Rb2Gi + c76 * beta_cav_LRb2Gi -
            c81 * beta_cav_Gi_bg * beta_cav_Gi_aGDP
        )
    # Concentration of active Gs beta-gamma subunit in the extracaveolar space
        D(beta_eca_Gs_bg) ~
        0.001 * (
            c75 * beta_eca_RGs_tot + c74 * beta_eca_LRGs_tot -
            c80 * beta_eca_Gs_bg * beta_eca_Gs_aGDP
        )
    # Concentration of active Gi beta-gamma subunit in the extracaveolar space
        D(beta_eca_Gi_bg) ~
        0.001 * (
            c77 * beta_eca_Rb2Gi + c76 * beta_eca_LRb2Gi -
            c81 * beta_eca_Gi_bg * beta_eca_Gi_aGDP
        )
    # Concentration of active Gs beta-gamma subunit in cytoplasm
        D(beta_cyt_Gs_bg) ~
        0.001 *
        (c75 * Rb1Gs_np + c74 * LRb1Gs_np - c80 * beta_cyt_Gs_bg * beta_cyt_Gs_aGDP)
    # Concentration of inactive Gs alpha subunit in caveolar subspace (di-phosphate)
        D(beta_cav_Gs_aGDP) ~ 0.001 * (c78 * beta_cav_Gs_aGTP - c80 * beta_cav_Gs_bg * beta_cav_Gs_aGDP)
    # Concentration of inactive Gi alpha subunit in caveolar subspace
        D(beta_cav_Gi_aGDP) ~ 0.001 * (c79 * beta_cav_Gi_aGTP - c81 * beta_cav_Gi_bg * beta_cav_Gi_aGDP)
    # Concentration of inactive Gs alpha subunit in the extracaveolar space (di-phosphate)
        D(beta_eca_Gs_aGDP) ~ 0.001 * (c78 * beta_eca_Gs_aGTP - c80 * beta_eca_Gs_bg * beta_eca_Gs_aGDP)
    # Concentration of inactive Gi alpha subunit in the extracaveolar space
        D(beta_eca_Gi_aGDP) ~ 0.001 * (c79 * beta_eca_Gi_aGTP - c81 * beta_eca_Gi_bg * beta_eca_Gi_aGDP)
    # Concentration of inactive Gs alpha subunit in cytoplasm
        D(beta_cyt_Gs_aGDP) ~ 0.001 * (c78 * beta_cyt_Gs_aGTP - c80 * beta_cyt_Gs_bg * beta_cyt_Gs_aGDP)
    # function Mod_AC()
    # only calculating constants, but does not compute derivative of state
    # variables
    # function Mod_PKA() in the other version %%%%%%%%%%
    # Concentration of free PKA RC subunits in the caveolar compartment
    pka_cav_RCf ~ c12 - pka_cav_ARC - pka_cav_A2RC - pka_cav_A2R
    # Caveolar concentration of PKA RC dimer with 1 cAMP molecule bound
        D(pka_cav_ARC) ~
        0.001 * (
            c19 * pka_cav_RCf * cAMP_cav - c22 * pka_cav_ARC -
            c20 * pka_cav_ARC * cAMP_cav + c23 * pka_cav_A2RC
        )
    # Caveolar concentration of PKA RC dimer with 2 cAMP molecules bound
        D(pka_cav_A2RC) ~
        0.001 * (
            c20 * pka_cav_ARC * cAMP_cav - (c23 + c21) * pka_cav_A2RC +
            c24 * pka_cav_A2R * pka_cav_C
        )
    # Caveolar concentration of PKA R subunit with 2 cAMP molecules bound
        D(pka_cav_A2R) ~ 0.001 * (c21 * pka_cav_A2RC - c24 * pka_cav_A2R * pka_cav_C)
    # Caveolar concentration of free PKA catalytic subunit
        D(pka_cav_C) ~
        0.001 * (
            c21 * pka_cav_A2RC - c24 * pka_cav_A2R * pka_cav_C + c18 * pka_cav_PKIC -
            c17 * (c14 - pka_cav_PKIC) * pka_cav_C
        )
    # Caveolar concentration of free PKI inactivated PKA C subunit
        D(pka_cav_PKIC) ~ 0.001 * (c17 * (c14 - pka_cav_PKIC) * pka_cav_C - c18 * pka_cav_PKIC)
    # Concentration of free PKA RC subunits in the Extracaveolar compartment
    pka_eca_RCf ~ c11 - pka_eca_ARC - pka_eca_A2RC - pka_eca_A2R
    # Extracaveolar rate of change in free cAMP through binding by PKA
    pka_eca_dcAMP ~ (
        -c19 * pka_eca_RCf * cAMP_eca + c25 * pka_eca_ARC -
        c20 * pka_eca_ARC * cAMP_eca + c26 * pka_eca_A2RC
    )
    # Extracaveolar concentration of PKA RC dimer with 1 cAMP molecule bound
        D(pka_eca_ARC) ~
        0.001 * (
            c19 * pka_eca_RCf * cAMP_eca - c25 * pka_eca_ARC -
            c20 * pka_eca_ARC * cAMP_eca + c26 * pka_eca_A2RC
        )
    # Extracaveolar concentration of PKA RC dimer with 2 cAMP molecules bound
        D(pka_eca_A2RC) ~
        0.001 * (
            c20 * pka_eca_ARC * cAMP_eca - (c26 + c21) * pka_eca_A2RC +
            c27 * pka_eca_A2R * pka_eca_C
        )
    # Extracaveolar concentration of PKA R subunit with 2 cAMP molecules bound
        D(pka_eca_A2R) ~ 0.001 * (c21 * pka_eca_A2RC - c27 * pka_eca_A2R * pka_eca_C)
    # Extracaveolar concentration of free PKA catalytic subunit
        D(pka_eca_C) ~
        0.001 * (
            c21 * pka_eca_A2RC - c27 * pka_eca_A2R * pka_eca_C + c18 * pka_eca_PKIC -
            c17 * (c15 - pka_eca_PKIC) * pka_eca_C
        )
    # Extracaveolar concentration of free PKI inactivated PKA C subunit
        D(pka_eca_PKIC) ~ 0.001 * (c17 * (c15 - pka_eca_PKIC) * pka_eca_C - c18 * pka_eca_PKIC)
    # Concentration of free PKA RC subunits in the Cytosolic compartment
    pka_cyt_RCf ~ c13 - pka_cyt_ARC - pka_cyt_A2RC - pka_cyt_A2R
    # Cytosolic concentration of PKA RC dimer with 1 cAMP molecule bound
        D(pka_cyt_ARC) ~
        0.001 * (
            c19 * pka_cyt_RCf * cAMP_cyt - c28 * pka_cyt_ARC -
            c20 * pka_cyt_ARC * cAMP_cyt + c29 * pka_cyt_A2RC
        )
    # Cytosolic concentration of PKA RC dimer with 2 cAMP molecules bound
        D(pka_cyt_A2RC) ~
        0.001 * (
            c20 * pka_cyt_ARC * cAMP_cyt - (c29 + c21) * pka_cyt_A2RC +
            c30 * pka_cyt_A2R * pka_cyt_C
        )
    # Cytosolic concentration of PKA R subunit with 2 cAMP molecules bound
        D(pka_cyt_A2R) ~ 0.001 * (c21 * pka_cyt_A2RC - c30 * pka_cyt_A2R * pka_cyt_C)
    # Cytosolic concentration of free PKA catalytic subunit
        D(pka_cyt_C) ~
        0.001 * (
            c21 * pka_cyt_A2RC - c30 * pka_cyt_A2R * pka_cyt_C + c18 * pka_cyt_PKIC -
            c17 * (c16 - pka_cyt_PKIC) * pka_cyt_C
        )
    # Cytosolic concentration of free PKI inactivated PKA C subunit
        D(pka_cyt_PKIC) ~ 0.001 * (c17 * (c16 - pka_cyt_PKIC) * pka_cyt_C - c18 * pka_cyt_PKIC)
    # function Mod_cAMP() in the other version
    # Caveolar rate of change in free cAMP through binding by PKA
    pka_cav_dcAMP ~ (
        -c19 * pka_cav_RCf * cAMP_cav + c22 * pka_cav_ARC -
        c20 * pka_cav_ARC * cAMP_cav + c23 * pka_cav_A2RC
    )
    # Cytosolic rate of change in free cAMP through binding by PKA
    pka_cyt_dcAMP ~ (
        -c19 * pka_cyt_RCf * cAMP_cyt + c28 * pka_cyt_ARC -
        c20 * pka_cyt_ARC * cAMP_cyt + c29 * pka_cyt_A2RC
    )
    # PDE
    # Rate of cAMP degradation by PDE2 in cytosolic subspace
    dcAMP_PDE2_cyt ~ c52 * c41 / (1.0 + c44 / cAMP_cyt)
    # Rate of cAMP degradation by PDE2 in extracaveolar subspace
    dcAMP_PDE2_eca ~ c51 * c41 / (1.0 + c44 / cAMP_eca)
    # Rate of cAMP degradation by PDE2 in caveolar subspace
    dcAMP_PDE2_cav ~ c50 * c41 / (1.0 + c44 / cAMP_cav)
    # Rate of cAMP degradation by PDE3 in caveolar subspace
    dcAMP_PDE3_cav ~ (c53 + (c47 - 1.0) * PDE3_P_cav) * c42 / (1.0 + c45 / cAMP_cav)
    # Rate of cAMP degradation by PDE4 in cytosolic subspace
    dcAMP_PDE4_cyt ~ (c57 + (c47 - 1.0) * PDE4_P_cyt) * c43 / (1.0 + c46 / cAMP_cyt)
    # Rate of cAMP degradation by PDE4 in extracaveolar subspace
    dcAMP_PDE4_eca ~ (c56 + (c47 - 1.0) * PDE4_P_eca) * c43 / (1.0 + c46 / cAMP_eca)
    # Rate of cAMP degradation by PDE4 in caveolar subspace
    dcAMP_PDE4_cav ~ (c55 + (c47 - 1.0) * PDE4_P_cav) * c43 / (1.0 + c46 / cAMP_cav)
    # Rate of cAMP degradation by PDE3 in cytosolic subspace
    dcAMP_PDE3_cyt ~ (c54 + (c47 - 1.0) * PDE3_P_cyt) * c42 / (1.0 + c45 / cAMP_cyt)
    camp_cAMP_cyt_pde ~ dcAMP_PDE2_cyt + dcAMP_PDE3_cyt + dcAMP_PDE4_cyt
    camp_cAMP_cyt_j1 ~ c9 * (cAMP_cav - cAMP_cyt) / c4
    camp_cAMP_cyt_j2 ~ c10 * (cAMP_eca - cAMP_cyt) / c4
    camp_cAMP_eca_pde ~ dcAMP_PDE2_eca + dcAMP_PDE4_eca
    camp_cAMP_eca_j2 ~ c10 * (cAMP_eca - cAMP_cyt) / c3
    camp_cAMP_eca_j1 ~ c8 * (cAMP_cav - cAMP_eca) / c3
    camp_cAMP_cav_pde ~ dcAMP_PDE2_cav + dcAMP_PDE3_cav + dcAMP_PDE4_cav
    camp_cAMP_cav_j2 ~ c9 * (cAMP_cav - cAMP_cyt) / c2
    camp_cAMP_cav_j1 ~ c8 * (cAMP_cav - cAMP_eca) / c2
    # ac
    #
    ac_kAC47_cyt_gsa ~ beta_cyt_Gs_aGTP^c107
    kAC47_cyt ~ c116 * (c114 + ac_kAC47_cyt_gsa / (c110 + ac_kAC47_cyt_gsa))
    ac_kAC56_cav_gsa ~ beta_cav_Gs_aGTP^c108
    gsi ~ beta_cav_Gs_aGTP^c109
    kAC56_cav ~ (
        c117 *
        (c115 + ac_kAC56_cav_gsa / (c111 + ac_kAC56_cav_gsa)) *
        (
            1.0 -
            (1.0 - c118 * gsi / (c113 + gsi)) * beta_cav_Gi_bg /
            (c112 + beta_cav_Gi_bg)
        )
    )
    ac_kAC47_eca_gsa ~ beta_eca_Gs_aGTP^c107
    kAC47_eca ~ c116 * (c114 + ac_kAC47_eca_gsa / (c110 + ac_kAC47_eca_gsa))
    ac_kAC56_cyt_gsa ~ beta_cyt_Gs_aGTP^c108
    kAC56_cyt ~ c117 * (c115 + ac_kAC56_cyt_gsa / (c111 + ac_kAC56_cyt_gsa))
    # Rate of cAMP production by AC type 4/7 in cytoplasm
    dcAMP_AC47_cyt ~ kAC47_cyt * c119 * c121
    # Rate of cAMP production by AC type 5/6 in cytoplasm
    dcAMP_AC56_cyt ~ kAC56_cyt * c123 * c121
    # Rate of cAMP production by AC type 5/6 in caveolar subspace
    dcAMP_AC56_cav ~ kAC56_cav * c120 * c121
    # Rate of cAMP production by AC type 4/7 in extracaveolar subspace
    dcAMP_AC47_eca ~ kAC47_eca * c122 * c121
    # Caveolar concentration of cAMP
        D(cAMP_cav) ~
        0.001 * (
            pka_cav_dcAMP + dcAMP_AC56_cav - camp_cAMP_cav_pde - camp_cAMP_cav_j1 -
            camp_cAMP_cav_j2
        )
    # Extracaveolar concentration of cAMP
        D(cAMP_eca) ~
        0.001 * (
            pka_eca_dcAMP + dcAMP_AC47_eca - camp_cAMP_eca_pde + camp_cAMP_eca_j1 -
            camp_cAMP_eca_j2
        )
    # Cytosolic concentration of cAMP
        D(cAMP_cyt) ~
        0.001 * (
            pka_cyt_dcAMP + dcAMP_AC47_cyt + dcAMP_AC56_cyt - camp_cAMP_cyt_pde +
            camp_cAMP_cyt_j1 +
            camp_cAMP_cyt_j2
        )
    # Mod_PDE_Phosphorylation() function
    # Concentration of phosphorylated PDE3 in the caveolar subspace
        D(PDE3_P_cav) ~ 0.001 * (c48 * pka_cav_C * (c53 - PDE3_P_cav) - c49 * PDE3_P_cav)
    # Concentration of phosphorylated PDE3 in the cytosolic subspace
        D(PDE3_P_cyt) ~ 0.001 * (c48 * pka_cyt_C * (c54 - PDE3_P_cyt) - c49 * PDE3_P_cyt)
    # Concentration of phosphorylated PDE4 in the caveolar subspace
        D(PDE4_P_cav) ~ 0.001 * (c48 * pka_cav_C * (c55 - PDE4_P_cav) - c49 * PDE4_P_cav)
    # Concentration of phosphorylated PDE4 in the extracaveolar subspace
        D(PDE4_P_eca) ~ 0.001 * (c48 * pka_eca_C * (c56 - PDE4_P_eca) - c49 * PDE4_P_eca)
    # Concentration of phosphorylated PDE4 in the cytosolic subspace
        D(PDE4_P_cyt) ~ 0.001 * (c48 * pka_cyt_C * (c57 - PDE4_P_cyt) - c49 * PDE4_P_cyt)
    # Mod_PP1_Inhibition()
    pp1_PP1f_cyt_sum ~ c38 - c37 + inhib1_p
    # Concentration of uninhibited PP1 in the cytosolic compartment
    PP1f_cyt ~ 0.5 * (sqrt(pp1_PP1f_cyt_sum^2.0 + 4.0 * c38 * c37) - pp1_PP1f_cyt_sum)
    di ~ c39 - inhib1_p
    # Concentration of phosphorylated PP1 inhibitor 1 (cytoplasmic)
        D(inhib1_p) ~
        0.001 * (
            c31 * pka_cyt_C * di / (c33 + di) -
            c32 * c40 * inhib1_p / (c34 + inhib1_p)
        )
    # Mod_Channel_Phosphorylation()
    # Substrates without AKAP
    # Fraction of phosphorylated PLB
        D(iup_f_plb) ~
        0.001 * (
            c132 * pka_cyt_C * (1.0 - iup_f_plb) / (c134 + 1.0 - iup_f_plb) -
            c133 * PP1f_cyt * iup_f_plb / (c135 + iup_f_plb)
        )
    # Fraction of phosphorylated Troponin
        D(f_tni) ~
        0.001 * (
            c147 * pka_cyt_C * (1.0 - f_tni) / (c149 + 1.0 - f_tni) -
            c148 * c40 * f_tni / (c150 + f_tni)
        )
    # Fraction of phosphorylated INa channels
        D(ina_f_ina) ~
        0.001 * (
            c130 * pka_cav_C * (1.0 - ina_f_ina) / (c128 + 1.0 - ina_f_ina) -
            c131 * c36 * ina_f_ina / (c129 + ina_f_ina)
        )
    # Fraction of phosphorylated INaK
        D(f_inak) ~
        0.001 * (
            c124 * pka_cav_C * (1.0 - f_inak) / (c126 + 1.0 - f_inak) -
            c125 * c36 * f_inak / (c127 + f_inak)
        )
    # Fraction of phosphorylated IKur channels
        D(f_ikur) ~
        0.001 * (
            c136 * pka_eca_C * (1.0 - f_ikur) / (c138 + 1.0 - f_ikur) -
            c137 * c35 * f_ikur / (c139 + f_ikur)
        )
    # Substrates with AKAP
    iks_sig_IKsp_dif ~ c146 - IKsp
    # Concentration of phosphorylated IKs channels
        D(IKsp) ~
        0.001 * (
            c140 * pka_eca_C * iks_sig_IKsp_dif / (c142 + iks_sig_IKsp_dif) -
            c141 * c35 * IKsp / (c143 + IKsp)
        )
    akap_sig_RyRp_dif ~ c162 - RyRp
        D(RyRp) ~
        0.001 * (
            c152 * pka_cav_C * akap_sig_RyRp_dif / (c154 + akap_sig_RyRp_dif) -
            c153 * c36 * RyRp / (c155 + RyRp)
        )
    akap_sig_ICaLp_dif ~ c164 - ICaLp
    # Concentration of phosphorylated L-type Calcium channels
        D(ICaLp) ~
        0.001 * (
            c157 * pka_cav_C * akap_sig_ICaLp_dif / (c159 + akap_sig_ICaLp_dif) -
            c158 * c36 * ICaLp / (c160 + ICaLp)
        )
    end
end
